// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type FileAssetReadReq struct {
	AssetId string `path:"asset_id,example=asset_01J8FILEEXAMPLE" validate:"required"`
}

type FileUploadPutReq struct {
	UploadId string `path:"upload_id,example=upload_01J8FILEEXAMPLE" validate:"required"`
	Token    string `header:"X-Upload-Token,example=signed_upload_token" validate:"required"`
}

type FileUploadPathReq struct {
	UploadId string `path:"upload_id,example=upload_01J8FILEEXAMPLE" validate:"required"`
}
