// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: v3/proto/identity.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Identity_RegisterLocalUser_FullMethodName     = "/identity.Identity/RegisterLocalUser"
	Identity_LoginLocalUser_FullMethodName        = "/identity.Identity/LoginLocalUser"
	Identity_StartSsoLogin_FullMethodName         = "/identity.Identity/StartSsoLogin"
	Identity_FinishSsoLogin_FullMethodName        = "/identity.Identity/FinishSsoLogin"
	Identity_RefreshSessionToken_FullMethodName   = "/identity.Identity/RefreshSessionToken"
	Identity_LogoutSession_FullMethodName         = "/identity.Identity/LogoutSession"
	Identity_GetCurrentUser_FullMethodName        = "/identity.Identity/GetCurrentUser"
	Identity_IntrospectAccessToken_FullMethodName = "/identity.Identity/IntrospectAccessToken"
)

// IdentityClient is the client API for Identity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityClient interface {
	RegisterLocalUser(ctx context.Context, in *RegisterLocalUserRequest, opts ...grpc.CallOption) (*RegisterLocalUserResponse, error)
	LoginLocalUser(ctx context.Context, in *LoginLocalUserRequest, opts ...grpc.CallOption) (*LoginLocalUserResponse, error)
	StartSsoLogin(ctx context.Context, in *StartSsoLoginRequest, opts ...grpc.CallOption) (*StartSsoLoginResponse, error)
	FinishSsoLogin(ctx context.Context, in *FinishSsoLoginRequest, opts ...grpc.CallOption) (*FinishSsoLoginResponse, error)
	RefreshSessionToken(ctx context.Context, in *RefreshSessionTokenRequest, opts ...grpc.CallOption) (*RefreshSessionTokenResponse, error)
	LogoutSession(ctx context.Context, in *LogoutSessionRequest, opts ...grpc.CallOption) (*LogoutSessionResponse, error)
	GetCurrentUser(ctx context.Context, in *GetCurrentUserRequest, opts ...grpc.CallOption) (*GetCurrentUserResponse, error)
	IntrospectAccessToken(ctx context.Context, in *IntrospectAccessTokenRequest, opts ...grpc.CallOption) (*IntrospectAccessTokenResponse, error)
}

type identityClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityClient(cc grpc.ClientConnInterface) IdentityClient {
	return &identityClient{cc}
}

func (c *identityClient) RegisterLocalUser(ctx context.Context, in *RegisterLocalUserRequest, opts ...grpc.CallOption) (*RegisterLocalUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterLocalUserResponse)
	err := c.cc.Invoke(ctx, Identity_RegisterLocalUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) LoginLocalUser(ctx context.Context, in *LoginLocalUserRequest, opts ...grpc.CallOption) (*LoginLocalUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginLocalUserResponse)
	err := c.cc.Invoke(ctx, Identity_LoginLocalUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) StartSsoLogin(ctx context.Context, in *StartSsoLoginRequest, opts ...grpc.CallOption) (*StartSsoLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSsoLoginResponse)
	err := c.cc.Invoke(ctx, Identity_StartSsoLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) FinishSsoLogin(ctx context.Context, in *FinishSsoLoginRequest, opts ...grpc.CallOption) (*FinishSsoLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishSsoLoginResponse)
	err := c.cc.Invoke(ctx, Identity_FinishSsoLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) RefreshSessionToken(ctx context.Context, in *RefreshSessionTokenRequest, opts ...grpc.CallOption) (*RefreshSessionTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshSessionTokenResponse)
	err := c.cc.Invoke(ctx, Identity_RefreshSessionToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) LogoutSession(ctx context.Context, in *LogoutSessionRequest, opts ...grpc.CallOption) (*LogoutSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutSessionResponse)
	err := c.cc.Invoke(ctx, Identity_LogoutSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) GetCurrentUser(ctx context.Context, in *GetCurrentUserRequest, opts ...grpc.CallOption) (*GetCurrentUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentUserResponse)
	err := c.cc.Invoke(ctx, Identity_GetCurrentUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) IntrospectAccessToken(ctx context.Context, in *IntrospectAccessTokenRequest, opts ...grpc.CallOption) (*IntrospectAccessTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntrospectAccessTokenResponse)
	err := c.cc.Invoke(ctx, Identity_IntrospectAccessToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServer is the server API for Identity service.
// All implementations must embed UnimplementedIdentityServer
// for forward compatibility.
type IdentityServer interface {
	RegisterLocalUser(context.Context, *RegisterLocalUserRequest) (*RegisterLocalUserResponse, error)
	LoginLocalUser(context.Context, *LoginLocalUserRequest) (*LoginLocalUserResponse, error)
	StartSsoLogin(context.Context, *StartSsoLoginRequest) (*StartSsoLoginResponse, error)
	FinishSsoLogin(context.Context, *FinishSsoLoginRequest) (*FinishSsoLoginResponse, error)
	RefreshSessionToken(context.Context, *RefreshSessionTokenRequest) (*RefreshSessionTokenResponse, error)
	LogoutSession(context.Context, *LogoutSessionRequest) (*LogoutSessionResponse, error)
	GetCurrentUser(context.Context, *GetCurrentUserRequest) (*GetCurrentUserResponse, error)
	IntrospectAccessToken(context.Context, *IntrospectAccessTokenRequest) (*IntrospectAccessTokenResponse, error)
	mustEmbedUnimplementedIdentityServer()
}

// UnimplementedIdentityServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServer struct{}

func (UnimplementedIdentityServer) RegisterLocalUser(context.Context, *RegisterLocalUserRequest) (*RegisterLocalUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterLocalUser not implemented")
}
func (UnimplementedIdentityServer) LoginLocalUser(context.Context, *LoginLocalUserRequest) (*LoginLocalUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginLocalUser not implemented")
}
func (UnimplementedIdentityServer) StartSsoLogin(context.Context, *StartSsoLoginRequest) (*StartSsoLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSsoLogin not implemented")
}
func (UnimplementedIdentityServer) FinishSsoLogin(context.Context, *FinishSsoLoginRequest) (*FinishSsoLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinishSsoLogin not implemented")
}
func (UnimplementedIdentityServer) RefreshSessionToken(context.Context, *RefreshSessionTokenRequest) (*RefreshSessionTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshSessionToken not implemented")
}
func (UnimplementedIdentityServer) LogoutSession(context.Context, *LogoutSessionRequest) (*LogoutSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LogoutSession not implemented")
}
func (UnimplementedIdentityServer) GetCurrentUser(context.Context, *GetCurrentUserRequest) (*GetCurrentUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentUser not implemented")
}
func (UnimplementedIdentityServer) IntrospectAccessToken(context.Context, *IntrospectAccessTokenRequest) (*IntrospectAccessTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IntrospectAccessToken not implemented")
}
func (UnimplementedIdentityServer) mustEmbedUnimplementedIdentityServer() {}
func (UnimplementedIdentityServer) testEmbeddedByValue()                  {}

// UnsafeIdentityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServer will
// result in compilation errors.
type UnsafeIdentityServer interface {
	mustEmbedUnimplementedIdentityServer()
}

func RegisterIdentityServer(s grpc.ServiceRegistrar, srv IdentityServer) {
	// If the following call panics, it indicates UnimplementedIdentityServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Identity_ServiceDesc, srv)
}

func _Identity_RegisterLocalUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterLocalUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).RegisterLocalUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_RegisterLocalUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).RegisterLocalUser(ctx, req.(*RegisterLocalUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_LoginLocalUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginLocalUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).LoginLocalUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_LoginLocalUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).LoginLocalUser(ctx, req.(*LoginLocalUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_StartSsoLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSsoLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).StartSsoLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_StartSsoLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).StartSsoLogin(ctx, req.(*StartSsoLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_FinishSsoLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishSsoLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).FinishSsoLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_FinishSsoLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).FinishSsoLogin(ctx, req.(*FinishSsoLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_RefreshSessionToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshSessionTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).RefreshSessionToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_RefreshSessionToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).RefreshSessionToken(ctx, req.(*RefreshSessionTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_LogoutSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).LogoutSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_LogoutSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).LogoutSession(ctx, req.(*LogoutSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_GetCurrentUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).GetCurrentUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_GetCurrentUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).GetCurrentUser(ctx, req.(*GetCurrentUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_IntrospectAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntrospectAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).IntrospectAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_IntrospectAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).IntrospectAccessToken(ctx, req.(*IntrospectAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Identity_ServiceDesc is the grpc.ServiceDesc for Identity service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Identity_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "identity.Identity",
	HandlerType: (*IdentityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterLocalUser",
			Handler:    _Identity_RegisterLocalUser_Handler,
		},
		{
			MethodName: "LoginLocalUser",
			Handler:    _Identity_LoginLocalUser_Handler,
		},
		{
			MethodName: "StartSsoLogin",
			Handler:    _Identity_StartSsoLogin_Handler,
		},
		{
			MethodName: "FinishSsoLogin",
			Handler:    _Identity_FinishSsoLogin_Handler,
		},
		{
			MethodName: "RefreshSessionToken",
			Handler:    _Identity_RefreshSessionToken_Handler,
		},
		{
			MethodName: "LogoutSession",
			Handler:    _Identity_LogoutSession_Handler,
		},
		{
			MethodName: "GetCurrentUser",
			Handler:    _Identity_GetCurrentUser_Handler,
		},
		{
			MethodName: "IntrospectAccessToken",
			Handler:    _Identity_IntrospectAccessToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v3/proto/identity.proto",
}
