// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: v3/proto/identity.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_GUEST       Role = 1
	Role_ROLE_MEMBER      Role = 2
	Role_ROLE_ADMIN       Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_GUEST",
		2: "ROLE_MEMBER",
		3: "ROLE_ADMIN",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_GUEST":       1,
		"ROLE_MEMBER":      2,
		"ROLE_ADMIN":       3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_v3_proto_identity_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_v3_proto_identity_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{0}
}

type AccountStatus int32

const (
	AccountStatus_ACCOUNT_STATUS_UNSPECIFIED AccountStatus = 0
	AccountStatus_ACCOUNT_STATUS_PENDING     AccountStatus = 1
	AccountStatus_ACCOUNT_STATUS_ACTIVE      AccountStatus = 2
	AccountStatus_ACCOUNT_STATUS_DISABLED    AccountStatus = 3
	AccountStatus_ACCOUNT_STATUS_LOCKED      AccountStatus = 4
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0: "ACCOUNT_STATUS_UNSPECIFIED",
		1: "ACCOUNT_STATUS_PENDING",
		2: "ACCOUNT_STATUS_ACTIVE",
		3: "ACCOUNT_STATUS_DISABLED",
		4: "ACCOUNT_STATUS_LOCKED",
	}
	AccountStatus_value = map[string]int32{
		"ACCOUNT_STATUS_UNSPECIFIED": 0,
		"ACCOUNT_STATUS_PENDING":     1,
		"ACCOUNT_STATUS_ACTIVE":      2,
		"ACCOUNT_STATUS_DISABLED":    3,
		"ACCOUNT_STATUS_LOCKED":      4,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v3_proto_identity_proto_enumTypes[1].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_v3_proto_identity_proto_enumTypes[1]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{1}
}

type AuthSource int32

const (
	AuthSource_AUTH_SOURCE_UNSPECIFIED AuthSource = 0
	AuthSource_AUTH_SOURCE_LOCAL       AuthSource = 1
	AuthSource_AUTH_SOURCE_SSO         AuthSource = 2
)

// Enum value maps for AuthSource.
var (
	AuthSource_name = map[int32]string{
		0: "AUTH_SOURCE_UNSPECIFIED",
		1: "AUTH_SOURCE_LOCAL",
		2: "AUTH_SOURCE_SSO",
	}
	AuthSource_value = map[string]int32{
		"AUTH_SOURCE_UNSPECIFIED": 0,
		"AUTH_SOURCE_LOCAL":       1,
		"AUTH_SOURCE_SSO":         2,
	}
)

func (x AuthSource) Enum() *AuthSource {
	p := new(AuthSource)
	*p = x
	return p
}

func (x AuthSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthSource) Descriptor() protoreflect.EnumDescriptor {
	return file_v3_proto_identity_proto_enumTypes[2].Descriptor()
}

func (AuthSource) Type() protoreflect.EnumType {
	return &file_v3_proto_identity_proto_enumTypes[2]
}

func (x AuthSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthSource.Descriptor instead.
func (AuthSource) EnumDescriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{2}
}

type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_UNSPECIFIED SessionStatus = 0
	SessionStatus_SESSION_STATUS_ACTIVE      SessionStatus = 1
	SessionStatus_SESSION_STATUS_REVOKED     SessionStatus = 2
	SessionStatus_SESSION_STATUS_EXPIRED     SessionStatus = 3
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "SESSION_STATUS_ACTIVE",
		2: "SESSION_STATUS_REVOKED",
		3: "SESSION_STATUS_EXPIRED",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED": 0,
		"SESSION_STATUS_ACTIVE":      1,
		"SESSION_STATUS_REVOKED":     2,
		"SESSION_STATUS_EXPIRED":     3,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v3_proto_identity_proto_enumTypes[3].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_v3_proto_identity_proto_enumTypes[3]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{3}
}

type TokenPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	TokenType     string                 `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenPair) Reset() {
	*x = TokenPair{}
	mi := &file_v3_proto_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPair) ProtoMessage() {}

func (x *TokenPair) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPair.ProtoReflect.Descriptor instead.
func (*TokenPair) Descriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{0}
}

func (x *TokenPair) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenPair) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenPair) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *TokenPair) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenPair) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CurrentUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Role          Role                   `protobuf:"varint,6,opt,name=role,proto3,enum=identity.Role" json:"role,omitempty"`
	Status        AccountStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=identity.AccountStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentUser) Reset() {
	*x = CurrentUser{}
	mi := &file_v3_proto_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentUser) ProtoMessage() {}

func (x *CurrentUser) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentUser.ProtoReflect.Descriptor instead.
func (*CurrentUser) Descriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{1}
}

func (x *CurrentUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CurrentUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CurrentUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CurrentUser) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CurrentUser) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *CurrentUser) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *CurrentUser) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

type SessionInfo struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SessionId  string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId     string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthSource AuthSource             `protobuf:"varint,3,opt,name=auth_source,json=authSource,proto3,enum=identity.AuthSource" json:"auth_source,omitempty"`
	ClientType string                 `protobuf:"bytes,4,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	DeviceId   string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceName string                 `protobuf:"bytes,6,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	Status     SessionStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=identity.SessionStatus" json:"status,omitempty"`
	// Unix 时间戳（秒）
	LastSeenAt int64 `protobuf:"varint,8,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	// Unix 时间戳（秒）
	ExpiresAt     int64 `protobuf:"varint,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_v3_proto_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{2}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionInfo) GetAuthSource() AuthSource {
	if x != nil {
		return x.AuthSource
	}
	return AuthSource_AUTH_SOURCE_UNSPECIFIED
}

func (x *SessionInfo) GetClientType() string {
	if x != nil {
		return x.ClientType
	}
	return ""
}

func (x *SessionInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SessionInfo) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *SessionInfo) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *SessionInfo) GetLastSeenAt() int64 {
	if x != nil {
		return x.LastSeenAt
	}
	return 0
}

func (x *SessionInfo) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type FederatedIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FederatedIdentity) Reset() {
	*x = FederatedIdentity{}
	mi := &file_v3_proto_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederatedIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederatedIdentity) ProtoMessage() {}

func (x *FederatedIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederatedIdentity.ProtoReflect.Descriptor instead.
func (*FederatedIdentity) Descriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{3}
}

func (x *FederatedIdentity) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *FederatedIdentity) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *FederatedIdentity) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *FederatedIdentity) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type RegisterLocalUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterLocalUserRequest) Reset() {
	*x = RegisterLocalUserRequest{}
	mi := &file_v3_proto_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterLocalUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterLocalUserRequest) ProtoMessage() {}

func (x *RegisterLocalUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterLocalUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterLocalUserRequest) Descriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterLocalUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterLocalUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterLocalUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterLocalUserRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type RegisterLocalUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentUser   *CurrentUser           `protobuf:"bytes,1,opt,name=current_user,json=currentUser,proto3" json:"current_user,omitempty"`
	TokenPair     *TokenPair             `protobuf:"bytes,2,opt,name=token_pair,json=tokenPair,proto3" json:"token_pair,omitempty"`
	SessionInfo   *SessionInfo           `protobuf:"bytes,3,opt,name=session_info,json=sessionInfo,proto3" json:"session_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterLocalUserResponse) Reset() {
	*x = RegisterLocalUserResponse{}
	mi := &file_v3_proto_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterLocalUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterLocalUserResponse) ProtoMessage() {}

func (x *RegisterLocalUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterLocalUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterLocalUserResponse) Descriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterLocalUserResponse) GetCurrentUser() *CurrentUser {
	if x != nil {
		return x.CurrentUser
	}
	return nil
}

func (x *RegisterLocalUserResponse) GetTokenPair() *TokenPair {
	if x != nil {
		return x.TokenPair
	}
	return nil
}

func (x *RegisterLocalUserResponse) GetSessionInfo() *SessionInfo {
	if x != nil {
		return x.SessionInfo
	}
	return nil
}

type LoginLocalUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 登录标识：允许 username 或 email
	LoginIdentifier string `protobuf:"bytes,1,opt,name=login_identifier,json=loginIdentifier,proto3" json:"login_identifier,omitempty"`
	Password        string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ClientType      string `protobuf:"bytes,3,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	DeviceId        string `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceName      string `protobuf:"bytes,5,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	UserAgent       string `protobuf:"bytes,6,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoginLocalUserRequest) Reset() {
	*x = LoginLocalUserRequest{}
	mi := &file_v3_proto_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginLocalUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginLocalUserRequest) ProtoMessage() {}

func (x *LoginLocalUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginLocalUserRequest.ProtoReflect.Descriptor instead.
func (*LoginLocalUserRequest) Descriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{6}
}

func (x *LoginLocalUserRequest) GetLoginIdentifier() string {
	if x != nil {
		return x.LoginIdentifier
	}
	return ""
}

func (x *LoginLocalUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginLocalUserRequest) GetClientType() string {
	if x != nil {
		return x.ClientType
	}
	return ""
}

func (x *LoginLocalUserRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LoginLocalUserRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *LoginLocalUserRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type LoginLocalUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenPair     *TokenPair             `protobuf:"bytes,1,opt,name=token_pair,json=tokenPair,proto3" json:"token_pair,omitempty"`
	CurrentUser   *CurrentUser           `protobuf:"bytes,2,opt,name=current_user,json=currentUser,proto3" json:"current_user,omitempty"`
	SessionInfo   *SessionInfo           `protobuf:"bytes,3,opt,name=session_info,json=sessionInfo,proto3" json:"session_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginLocalUserResponse) Reset() {
	*x = LoginLocalUserResponse{}
	mi := &file_v3_proto_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginLocalUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginLocalUserResponse) ProtoMessage() {}

func (x *LoginLocalUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginLocalUserResponse.ProtoReflect.Descriptor instead.
func (*LoginLocalUserResponse) Descriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{7}
}

func (x *LoginLocalUserResponse) GetTokenPair() *TokenPair {
	if x != nil {
		return x.TokenPair
	}
	return nil
}

func (x *LoginLocalUserResponse) GetCurrentUser() *CurrentUser {
	if x != nil {
		return x.CurrentUser
	}
	return nil
}

func (x *LoginLocalUserResponse) GetSessionInfo() *SessionInfo {
	if x != nil {
		return x.SessionInfo
	}
	return nil
}

type StartSsoLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	RedirectUri   string                 `protobuf:"bytes,2,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSsoLoginRequest) Reset() {
	*x = StartSsoLoginRequest{}
	mi := &file_v3_proto_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSsoLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSsoLoginRequest) ProtoMessage() {}

func (x *StartSsoLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSsoLoginRequest.ProtoReflect.Descriptor instead.
func (*StartSsoLoginRequest) Descriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{8}
}

func (x *StartSsoLoginRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *StartSsoLoginRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *StartSsoLoginRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type StartSsoLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	AuthUrl       string                 `protobuf:"bytes,2,opt,name=auth_url,json=authUrl,proto3" json:"auth_url,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSsoLoginResponse) Reset() {
	*x = StartSsoLoginResponse{}
	mi := &file_v3_proto_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSsoLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSsoLoginResponse) ProtoMessage() {}

func (x *StartSsoLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSsoLoginResponse.ProtoReflect.Descriptor instead.
func (*StartSsoLoginResponse) Descriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{9}
}

func (x *StartSsoLoginResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *StartSsoLoginResponse) GetAuthUrl() string {
	if x != nil {
		return x.AuthUrl
	}
	return ""
}

func (x *StartSsoLoginResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type FinishSsoLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	RedirectUri   string                 `protobuf:"bytes,4,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	ClientType    string                 `protobuf:"bytes,5,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	DeviceId      string                 `protobuf:"bytes,6,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceName    string                 `protobuf:"bytes,7,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	UserAgent     string                 `protobuf:"bytes,8,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishSsoLoginRequest) Reset() {
	*x = FinishSsoLoginRequest{}
	mi := &file_v3_proto_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishSsoLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishSsoLoginRequest) ProtoMessage() {}

func (x *FinishSsoLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishSsoLoginRequest.ProtoReflect.Descriptor instead.
func (*FinishSsoLoginRequest) Descriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{10}
}

func (x *FinishSsoLoginRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *FinishSsoLoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *FinishSsoLoginRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *FinishSsoLoginRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *FinishSsoLoginRequest) GetClientType() string {
	if x != nil {
		return x.ClientType
	}
	return ""
}

func (x *FinishSsoLoginRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *FinishSsoLoginRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *FinishSsoLoginRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type FinishSsoLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenPair     *TokenPair             `protobuf:"bytes,1,opt,name=token_pair,json=tokenPair,proto3" json:"token_pair,omitempty"`
	CurrentUser   *CurrentUser           `protobuf:"bytes,2,opt,name=current_user,json=currentUser,proto3" json:"current_user,omitempty"`
	SessionInfo   *SessionInfo           `protobuf:"bytes,3,opt,name=session_info,json=sessionInfo,proto3" json:"session_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishSsoLoginResponse) Reset() {
	*x = FinishSsoLoginResponse{}
	mi := &file_v3_proto_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishSsoLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishSsoLoginResponse) ProtoMessage() {}

func (x *FinishSsoLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishSsoLoginResponse.ProtoReflect.Descriptor instead.
func (*FinishSsoLoginResponse) Descriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{11}
}

func (x *FinishSsoLoginResponse) GetTokenPair() *TokenPair {
	if x != nil {
		return x.TokenPair
	}
	return nil
}

func (x *FinishSsoLoginResponse) GetCurrentUser() *CurrentUser {
	if x != nil {
		return x.CurrentUser
	}
	return nil
}

func (x *FinishSsoLoginResponse) GetSessionInfo() *SessionInfo {
	if x != nil {
		return x.SessionInfo
	}
	return nil
}

type RefreshSessionTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	UserAgent     string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshSessionTokenRequest) Reset() {
	*x = RefreshSessionTokenRequest{}
	mi := &file_v3_proto_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSessionTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSessionTokenRequest) ProtoMessage() {}

func (x *RefreshSessionTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSessionTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshSessionTokenRequest) Descriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{12}
}

func (x *RefreshSessionTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshSessionTokenRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type RefreshSessionTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// refresh token 轮换：每次成功刷新返回新的 access + refresh
	TokenPair     *TokenPair   `protobuf:"bytes,1,opt,name=token_pair,json=tokenPair,proto3" json:"token_pair,omitempty"`
	SessionInfo   *SessionInfo `protobuf:"bytes,2,opt,name=session_info,json=sessionInfo,proto3" json:"session_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshSessionTokenResponse) Reset() {
	*x = RefreshSessionTokenResponse{}
	mi := &file_v3_proto_identity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSessionTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSessionTokenResponse) ProtoMessage() {}

func (x *RefreshSessionTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_identity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSessionTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshSessionTokenResponse) Descriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{13}
}

func (x *RefreshSessionTokenResponse) GetTokenPair() *TokenPair {
	if x != nil {
		return x.TokenPair
	}
	return nil
}

func (x *RefreshSessionTokenResponse) GetSessionInfo() *SessionInfo {
	if x != nil {
		return x.SessionInfo
	}
	return nil
}

// LogoutSession：session_id 须由可信调用方（gateway）在调用 RPC 前从 access token
// 上下文中解析并填入，用于“当前会话登出”；refresh_token 可选，用于同时吊销轮换链。
type LogoutSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutSessionRequest) Reset() {
	*x = LogoutSessionRequest{}
	mi := &file_v3_proto_identity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutSessionRequest) ProtoMessage() {}

func (x *LogoutSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_identity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutSessionRequest.ProtoReflect.Descriptor instead.
func (*LogoutSessionRequest) Descriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{14}
}

func (x *LogoutSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LogoutSessionRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutSessionResponse) Reset() {
	*x = LogoutSessionResponse{}
	mi := &file_v3_proto_identity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutSessionResponse) ProtoMessage() {}

func (x *LogoutSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_identity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutSessionResponse.ProtoReflect.Descriptor instead.
func (*LogoutSessionResponse) Descriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{15}
}

func (x *LogoutSessionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetCurrentUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserRequest) Reset() {
	*x = GetCurrentUserRequest{}
	mi := &file_v3_proto_identity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserRequest) ProtoMessage() {}

func (x *GetCurrentUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_identity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentUserRequest) Descriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{16}
}

func (x *GetCurrentUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetCurrentUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentUser   *CurrentUser           `protobuf:"bytes,1,opt,name=current_user,json=currentUser,proto3" json:"current_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserResponse) Reset() {
	*x = GetCurrentUserResponse{}
	mi := &file_v3_proto_identity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserResponse) ProtoMessage() {}

func (x *GetCurrentUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_identity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentUserResponse) Descriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{17}
}

func (x *GetCurrentUserResponse) GetCurrentUser() *CurrentUser {
	if x != nil {
		return x.CurrentUser
	}
	return nil
}

type IntrospectAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrospectAccessTokenRequest) Reset() {
	*x = IntrospectAccessTokenRequest{}
	mi := &file_v3_proto_identity_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectAccessTokenRequest) ProtoMessage() {}

func (x *IntrospectAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_identity_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*IntrospectAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{18}
}

func (x *IntrospectAccessTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type IntrospectAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          Role                   `protobuf:"varint,3,opt,name=role,proto3,enum=identity.Role" json:"role,omitempty"`
	AccountStatus AccountStatus          `protobuf:"varint,4,opt,name=account_status,json=accountStatus,proto3,enum=identity.AccountStatus" json:"account_status,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AuthSource    AuthSource             `protobuf:"varint,6,opt,name=auth_source,json=authSource,proto3,enum=identity.AuthSource" json:"auth_source,omitempty"`
	// access token 过期时间，Unix 时间戳（秒）
	ExpiresAt     int64 `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrospectAccessTokenResponse) Reset() {
	*x = IntrospectAccessTokenResponse{}
	mi := &file_v3_proto_identity_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectAccessTokenResponse) ProtoMessage() {}

func (x *IntrospectAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_identity_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*IntrospectAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_v3_proto_identity_proto_rawDescGZIP(), []int{19}
}

func (x *IntrospectAccessTokenResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *IntrospectAccessTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IntrospectAccessTokenResponse) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *IntrospectAccessTokenResponse) GetAccountStatus() AccountStatus {
	if x != nil {
		return x.AccountStatus
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

func (x *IntrospectAccessTokenResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *IntrospectAccessTokenResponse) GetAuthSource() AuthSource {
	if x != nil {
		return x.AuthSource
	}
	return AuthSource_AUTH_SOURCE_UNSPECIFIED
}

func (x *IntrospectAccessTokenResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_v3_proto_identity_proto protoreflect.FileDescriptor

const file_v3_proto_identity_proto_rawDesc = "" +
	"\n" +
	"\x17v3/proto/identity.proto\x12\bidentity\"\xb0\x01\n" +
	"\tTokenPair\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"\xe8\x01\n" +
	"\vCurrentUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\x12\"\n" +
	"\x04role\x18\x06 \x01(\x0e2\x0e.identity.RoleR\x04role\x12/\n" +
	"\x06status\x18\a \x01(\x0e2\x17.identity.AccountStatusR\x06status\"\xcd\x02\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x125\n" +
	"\vauth_source\x18\x03 \x01(\x0e2\x14.identity.AuthSourceR\n" +
	"authSource\x12\x1f\n" +
	"\vclient_type\x18\x04 \x01(\tR\n" +
	"clientType\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x06 \x01(\tR\n" +
	"deviceName\x12/\n" +
	"\x06status\x18\a \x01(\x0e2\x17.identity.SessionStatusR\x06status\x12 \n" +
	"\flast_seen_at\x18\b \x01(\x03R\n" +
	"lastSeenAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\t \x01(\x03R\texpiresAt\"\x82\x01\n" +
	"\x11FederatedIdentity\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\"\x84\x01\n" +
	"\x18RegisterLocalUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\"\xc3\x01\n" +
	"\x19RegisterLocalUserResponse\x128\n" +
	"\fcurrent_user\x18\x01 \x01(\v2\x15.identity.CurrentUserR\vcurrentUser\x122\n" +
	"\n" +
	"token_pair\x18\x02 \x01(\v2\x13.identity.TokenPairR\ttokenPair\x128\n" +
	"\fsession_info\x18\x03 \x01(\v2\x15.identity.SessionInfoR\vsessionInfo\"\xed\x01\n" +
	"\x15LoginLocalUserRequest\x12)\n" +
	"\x10login_identifier\x18\x01 \x01(\tR\x0floginIdentifier\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1f\n" +
	"\vclient_type\x18\x03 \x01(\tR\n" +
	"clientType\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x05 \x01(\tR\n" +
	"deviceName\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x06 \x01(\tR\tuserAgentJ\x04\b\a\x10\bR\tclient_ip\"\xc0\x01\n" +
	"\x16LoginLocalUserResponse\x122\n" +
	"\n" +
	"token_pair\x18\x01 \x01(\v2\x13.identity.TokenPairR\ttokenPair\x128\n" +
	"\fcurrent_user\x18\x02 \x01(\v2\x15.identity.CurrentUserR\vcurrentUser\x128\n" +
	"\fsession_info\x18\x03 \x01(\v2\x15.identity.SessionInfoR\vsessionInfo\"k\n" +
	"\x14StartSsoLoginRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12!\n" +
	"\fredirect_uri\x18\x02 \x01(\tR\vredirectUri\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\"d\n" +
	"\x15StartSsoLoginResponse\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x19\n" +
	"\bauth_url\x18\x02 \x01(\tR\aauthUrl\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\"\x8f\x02\n" +
	"\x15FinishSsoLoginRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12!\n" +
	"\fredirect_uri\x18\x04 \x01(\tR\vredirectUri\x12\x1f\n" +
	"\vclient_type\x18\x05 \x01(\tR\n" +
	"clientType\x12\x1b\n" +
	"\tdevice_id\x18\x06 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\a \x01(\tR\n" +
	"deviceName\x12\x1d\n" +
	"\n" +
	"user_agent\x18\b \x01(\tR\tuserAgentJ\x04\b\t\x10\n" +
	"R\tclient_ip\"\xc0\x01\n" +
	"\x16FinishSsoLoginResponse\x122\n" +
	"\n" +
	"token_pair\x18\x01 \x01(\v2\x13.identity.TokenPairR\ttokenPair\x128\n" +
	"\fcurrent_user\x18\x02 \x01(\v2\x15.identity.CurrentUserR\vcurrentUser\x128\n" +
	"\fsession_info\x18\x03 \x01(\v2\x15.identity.SessionInfoR\vsessionInfo\"q\n" +
	"\x1aRefreshSessionTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgentJ\x04\b\x02\x10\x03R\tclient_ip\"\x8b\x01\n" +
	"\x1bRefreshSessionTokenResponse\x122\n" +
	"\n" +
	"token_pair\x18\x01 \x01(\v2\x13.identity.TokenPairR\ttokenPair\x128\n" +
	"\fsession_info\x18\x02 \x01(\v2\x15.identity.SessionInfoR\vsessionInfo\"Z\n" +
	"\x14LogoutSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"'\n" +
	"\x15LogoutSessionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"0\n" +
	"\x15GetCurrentUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"R\n" +
	"\x16GetCurrentUserResponse\x128\n" +
	"\fcurrent_user\x18\x01 \x01(\v2\x15.identity.CurrentUserR\vcurrentUser\"A\n" +
	"\x1cIntrospectAccessTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\xa9\x02\n" +
	"\x1dIntrospectAccessTokenResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\"\n" +
	"\x04role\x18\x03 \x01(\x0e2\x0e.identity.RoleR\x04role\x12>\n" +
	"\x0eaccount_status\x18\x04 \x01(\x0e2\x17.identity.AccountStatusR\raccountStatus\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x125\n" +
	"\vauth_source\x18\x06 \x01(\x0e2\x14.identity.AuthSourceR\n" +
	"authSource\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt*M\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"ROLE_GUEST\x10\x01\x12\x0f\n" +
	"\vROLE_MEMBER\x10\x02\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x03*\x9e\x01\n" +
	"\rAccountStatus\x12\x1e\n" +
	"\x1aACCOUNT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ACCOUNT_STATUS_PENDING\x10\x01\x12\x19\n" +
	"\x15ACCOUNT_STATUS_ACTIVE\x10\x02\x12\x1b\n" +
	"\x17ACCOUNT_STATUS_DISABLED\x10\x03\x12\x19\n" +
	"\x15ACCOUNT_STATUS_LOCKED\x10\x04*U\n" +
	"\n" +
	"AuthSource\x12\x1b\n" +
	"\x17AUTH_SOURCE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11AUTH_SOURCE_LOCAL\x10\x01\x12\x13\n" +
	"\x0fAUTH_SOURCE_SSO\x10\x02*\x82\x01\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SESSION_STATUS_ACTIVE\x10\x01\x12\x1a\n" +
	"\x16SESSION_STATUS_REVOKED\x10\x02\x12\x1a\n" +
	"\x16SESSION_STATUS_EXPIRED\x10\x032\xd9\x05\n" +
	"\bIdentity\x12\\\n" +
	"\x11RegisterLocalUser\x12\".identity.RegisterLocalUserRequest\x1a#.identity.RegisterLocalUserResponse\x12S\n" +
	"\x0eLoginLocalUser\x12\x1f.identity.LoginLocalUserRequest\x1a .identity.LoginLocalUserResponse\x12P\n" +
	"\rStartSsoLogin\x12\x1e.identity.StartSsoLoginRequest\x1a\x1f.identity.StartSsoLoginResponse\x12S\n" +
	"\x0eFinishSsoLogin\x12\x1f.identity.FinishSsoLoginRequest\x1a .identity.FinishSsoLoginResponse\x12b\n" +
	"\x13RefreshSessionToken\x12$.identity.RefreshSessionTokenRequest\x1a%.identity.RefreshSessionTokenResponse\x12P\n" +
	"\rLogoutSession\x12\x1e.identity.LogoutSessionRequest\x1a\x1f.identity.LogoutSessionResponse\x12S\n" +
	"\x0eGetCurrentUser\x12\x1f.identity.GetCurrentUserRequest\x1a .identity.GetCurrentUserResponse\x12h\n" +
	"\x15IntrospectAccessToken\x12&.identity.IntrospectAccessTokenRequest\x1a'.identity.IntrospectAccessTokenResponseB\x16Z\x14services/identity/pbb\x06proto3"

var (
	file_v3_proto_identity_proto_rawDescOnce sync.Once
	file_v3_proto_identity_proto_rawDescData []byte
)

func file_v3_proto_identity_proto_rawDescGZIP() []byte {
	file_v3_proto_identity_proto_rawDescOnce.Do(func() {
		file_v3_proto_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v3_proto_identity_proto_rawDesc), len(file_v3_proto_identity_proto_rawDesc)))
	})
	return file_v3_proto_identity_proto_rawDescData
}

var file_v3_proto_identity_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_v3_proto_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_v3_proto_identity_proto_goTypes = []any{
	(Role)(0),                             // 0: identity.Role
	(AccountStatus)(0),                    // 1: identity.AccountStatus
	(AuthSource)(0),                       // 2: identity.AuthSource
	(SessionStatus)(0),                    // 3: identity.SessionStatus
	(*TokenPair)(nil),                     // 4: identity.TokenPair
	(*CurrentUser)(nil),                   // 5: identity.CurrentUser
	(*SessionInfo)(nil),                   // 6: identity.SessionInfo
	(*FederatedIdentity)(nil),             // 7: identity.FederatedIdentity
	(*RegisterLocalUserRequest)(nil),      // 8: identity.RegisterLocalUserRequest
	(*RegisterLocalUserResponse)(nil),     // 9: identity.RegisterLocalUserResponse
	(*LoginLocalUserRequest)(nil),         // 10: identity.LoginLocalUserRequest
	(*LoginLocalUserResponse)(nil),        // 11: identity.LoginLocalUserResponse
	(*StartSsoLoginRequest)(nil),          // 12: identity.StartSsoLoginRequest
	(*StartSsoLoginResponse)(nil),         // 13: identity.StartSsoLoginResponse
	(*FinishSsoLoginRequest)(nil),         // 14: identity.FinishSsoLoginRequest
	(*FinishSsoLoginResponse)(nil),        // 15: identity.FinishSsoLoginResponse
	(*RefreshSessionTokenRequest)(nil),    // 16: identity.RefreshSessionTokenRequest
	(*RefreshSessionTokenResponse)(nil),   // 17: identity.RefreshSessionTokenResponse
	(*LogoutSessionRequest)(nil),          // 18: identity.LogoutSessionRequest
	(*LogoutSessionResponse)(nil),         // 19: identity.LogoutSessionResponse
	(*GetCurrentUserRequest)(nil),         // 20: identity.GetCurrentUserRequest
	(*GetCurrentUserResponse)(nil),        // 21: identity.GetCurrentUserResponse
	(*IntrospectAccessTokenRequest)(nil),  // 22: identity.IntrospectAccessTokenRequest
	(*IntrospectAccessTokenResponse)(nil), // 23: identity.IntrospectAccessTokenResponse
}
var file_v3_proto_identity_proto_depIdxs = []int32{
	0,  // 0: identity.CurrentUser.role:type_name -> identity.Role
	1,  // 1: identity.CurrentUser.status:type_name -> identity.AccountStatus
	2,  // 2: identity.SessionInfo.auth_source:type_name -> identity.AuthSource
	3,  // 3: identity.SessionInfo.status:type_name -> identity.SessionStatus
	5,  // 4: identity.RegisterLocalUserResponse.current_user:type_name -> identity.CurrentUser
	4,  // 5: identity.RegisterLocalUserResponse.token_pair:type_name -> identity.TokenPair
	6,  // 6: identity.RegisterLocalUserResponse.session_info:type_name -> identity.SessionInfo
	4,  // 7: identity.LoginLocalUserResponse.token_pair:type_name -> identity.TokenPair
	5,  // 8: identity.LoginLocalUserResponse.current_user:type_name -> identity.CurrentUser
	6,  // 9: identity.LoginLocalUserResponse.session_info:type_name -> identity.SessionInfo
	4,  // 10: identity.FinishSsoLoginResponse.token_pair:type_name -> identity.TokenPair
	5,  // 11: identity.FinishSsoLoginResponse.current_user:type_name -> identity.CurrentUser
	6,  // 12: identity.FinishSsoLoginResponse.session_info:type_name -> identity.SessionInfo
	4,  // 13: identity.RefreshSessionTokenResponse.token_pair:type_name -> identity.TokenPair
	6,  // 14: identity.RefreshSessionTokenResponse.session_info:type_name -> identity.SessionInfo
	5,  // 15: identity.GetCurrentUserResponse.current_user:type_name -> identity.CurrentUser
	0,  // 16: identity.IntrospectAccessTokenResponse.role:type_name -> identity.Role
	1,  // 17: identity.IntrospectAccessTokenResponse.account_status:type_name -> identity.AccountStatus
	2,  // 18: identity.IntrospectAccessTokenResponse.auth_source:type_name -> identity.AuthSource
	8,  // 19: identity.Identity.RegisterLocalUser:input_type -> identity.RegisterLocalUserRequest
	10, // 20: identity.Identity.LoginLocalUser:input_type -> identity.LoginLocalUserRequest
	12, // 21: identity.Identity.StartSsoLogin:input_type -> identity.StartSsoLoginRequest
	14, // 22: identity.Identity.FinishSsoLogin:input_type -> identity.FinishSsoLoginRequest
	16, // 23: identity.Identity.RefreshSessionToken:input_type -> identity.RefreshSessionTokenRequest
	18, // 24: identity.Identity.LogoutSession:input_type -> identity.LogoutSessionRequest
	20, // 25: identity.Identity.GetCurrentUser:input_type -> identity.GetCurrentUserRequest
	22, // 26: identity.Identity.IntrospectAccessToken:input_type -> identity.IntrospectAccessTokenRequest
	9,  // 27: identity.Identity.RegisterLocalUser:output_type -> identity.RegisterLocalUserResponse
	11, // 28: identity.Identity.LoginLocalUser:output_type -> identity.LoginLocalUserResponse
	13, // 29: identity.Identity.StartSsoLogin:output_type -> identity.StartSsoLoginResponse
	15, // 30: identity.Identity.FinishSsoLogin:output_type -> identity.FinishSsoLoginResponse
	17, // 31: identity.Identity.RefreshSessionToken:output_type -> identity.RefreshSessionTokenResponse
	19, // 32: identity.Identity.LogoutSession:output_type -> identity.LogoutSessionResponse
	21, // 33: identity.Identity.GetCurrentUser:output_type -> identity.GetCurrentUserResponse
	23, // 34: identity.Identity.IntrospectAccessToken:output_type -> identity.IntrospectAccessTokenResponse
	27, // [27:35] is the sub-list for method output_type
	19, // [19:27] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_v3_proto_identity_proto_init() }
func file_v3_proto_identity_proto_init() {
	if File_v3_proto_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v3_proto_identity_proto_rawDesc), len(file_v3_proto_identity_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v3_proto_identity_proto_goTypes,
		DependencyIndexes: file_v3_proto_identity_proto_depIdxs,
		EnumInfos:         file_v3_proto_identity_proto_enumTypes,
		MessageInfos:      file_v3_proto_identity_proto_msgTypes,
	}.Build()
	File_v3_proto_identity_proto = out.File
	file_v3_proto_identity_proto_goTypes = nil
	file_v3_proto_identity_proto_depIdxs = nil
}
