// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: content.proto

package content

import (
	"context"

	"github.com/HappyLadySauce/Beehive-Blog-V3/services/content/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ArchiveContentRequest          = pb.ArchiveContentRequest
	ArchiveContentResponse         = pb.ArchiveContentResponse
	ContentDetail                  = pb.ContentDetail
	ContentRevisionDetail          = pb.ContentRevisionDetail
	ContentRevisionSummary         = pb.ContentRevisionSummary
	ContentRelationView            = pb.ContentRelationView
	ContentSummary                 = pb.ContentSummary
	ContentTag                     = pb.ContentTag
	CreateContentRequest           = pb.CreateContentRequest
	CreateContentResponse          = pb.CreateContentResponse
	CreateContentRelationRequest   = pb.CreateContentRelationRequest
	CreateContentRelationResponse  = pb.CreateContentRelationResponse
	CreateTagRequest               = pb.CreateTagRequest
	CreateTagResponse              = pb.CreateTagResponse
	DeleteContentRelationRequest   = pb.DeleteContentRelationRequest
	DeleteContentRelationResponse  = pb.DeleteContentRelationResponse
	DeleteTagRequest               = pb.DeleteTagRequest
	DeleteTagResponse              = pb.DeleteTagResponse
	GetContentRequest              = pb.GetContentRequest
	GetContentResponse             = pb.GetContentResponse
	GetContentRevisionRequest      = pb.GetContentRevisionRequest
	GetContentRevisionResponse     = pb.GetContentRevisionResponse
	GetPublicContentBySlugRequest  = pb.GetPublicContentBySlugRequest
	GetPublicContentBySlugResponse = pb.GetPublicContentBySlugResponse
	ListContentRelationsRequest    = pb.ListContentRelationsRequest
	ListContentRelationsResponse   = pb.ListContentRelationsResponse
	ListContentRevisionsRequest    = pb.ListContentRevisionsRequest
	ListContentRevisionsResponse   = pb.ListContentRevisionsResponse
	ListPublicContentsRequest      = pb.ListPublicContentsRequest
	ListPublicContentsResponse     = pb.ListPublicContentsResponse
	ListStudioContentsRequest      = pb.ListStudioContentsRequest
	ListStudioContentsResponse     = pb.ListStudioContentsResponse
	ListTagsRequest                = pb.ListTagsRequest
	ListTagsResponse               = pb.ListTagsResponse
	PingRequest                    = pb.PingRequest
	PingResponse                   = pb.PingResponse
	UpdateContentRequest           = pb.UpdateContentRequest
	UpdateContentResponse          = pb.UpdateContentResponse
	UpdateTagRequest               = pb.UpdateTagRequest
	UpdateTagResponse              = pb.UpdateTagResponse

	Content interface {
		CreateContent(ctx context.Context, in *CreateContentRequest, opts ...grpc.CallOption) (*CreateContentResponse, error)
		UpdateContent(ctx context.Context, in *UpdateContentRequest, opts ...grpc.CallOption) (*UpdateContentResponse, error)
		GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*GetContentResponse, error)
		ListStudioContents(ctx context.Context, in *ListStudioContentsRequest, opts ...grpc.CallOption) (*ListStudioContentsResponse, error)
		ArchiveContent(ctx context.Context, in *ArchiveContentRequest, opts ...grpc.CallOption) (*ArchiveContentResponse, error)
		ListContentRevisions(ctx context.Context, in *ListContentRevisionsRequest, opts ...grpc.CallOption) (*ListContentRevisionsResponse, error)
		GetContentRevision(ctx context.Context, in *GetContentRevisionRequest, opts ...grpc.CallOption) (*GetContentRevisionResponse, error)
		CreateContentRelation(ctx context.Context, in *CreateContentRelationRequest, opts ...grpc.CallOption) (*CreateContentRelationResponse, error)
		DeleteContentRelation(ctx context.Context, in *DeleteContentRelationRequest, opts ...grpc.CallOption) (*DeleteContentRelationResponse, error)
		ListContentRelations(ctx context.Context, in *ListContentRelationsRequest, opts ...grpc.CallOption) (*ListContentRelationsResponse, error)
		CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error)
		UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*UpdateTagResponse, error)
		DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error)
		ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error)
		ListPublicContents(ctx context.Context, in *ListPublicContentsRequest, opts ...grpc.CallOption) (*ListPublicContentsResponse, error)
		GetPublicContentBySlug(ctx context.Context, in *GetPublicContentBySlugRequest, opts ...grpc.CallOption) (*GetPublicContentBySlugResponse, error)
		Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	}

	defaultContent struct {
		cli zrpc.Client
	}
)

func NewContent(cli zrpc.Client) Content {
	return &defaultContent{
		cli: cli,
	}
}

func (m *defaultContent) CreateContent(ctx context.Context, in *CreateContentRequest, opts ...grpc.CallOption) (*CreateContentResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.CreateContent(ctx, in, opts...)
}

func (m *defaultContent) UpdateContent(ctx context.Context, in *UpdateContentRequest, opts ...grpc.CallOption) (*UpdateContentResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.UpdateContent(ctx, in, opts...)
}

func (m *defaultContent) GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*GetContentResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.GetContent(ctx, in, opts...)
}

func (m *defaultContent) ListStudioContents(ctx context.Context, in *ListStudioContentsRequest, opts ...grpc.CallOption) (*ListStudioContentsResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.ListStudioContents(ctx, in, opts...)
}

func (m *defaultContent) ArchiveContent(ctx context.Context, in *ArchiveContentRequest, opts ...grpc.CallOption) (*ArchiveContentResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.ArchiveContent(ctx, in, opts...)
}

func (m *defaultContent) ListContentRevisions(ctx context.Context, in *ListContentRevisionsRequest, opts ...grpc.CallOption) (*ListContentRevisionsResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.ListContentRevisions(ctx, in, opts...)
}

func (m *defaultContent) GetContentRevision(ctx context.Context, in *GetContentRevisionRequest, opts ...grpc.CallOption) (*GetContentRevisionResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.GetContentRevision(ctx, in, opts...)
}

func (m *defaultContent) CreateContentRelation(ctx context.Context, in *CreateContentRelationRequest, opts ...grpc.CallOption) (*CreateContentRelationResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.CreateContentRelation(ctx, in, opts...)
}

func (m *defaultContent) DeleteContentRelation(ctx context.Context, in *DeleteContentRelationRequest, opts ...grpc.CallOption) (*DeleteContentRelationResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.DeleteContentRelation(ctx, in, opts...)
}

func (m *defaultContent) ListContentRelations(ctx context.Context, in *ListContentRelationsRequest, opts ...grpc.CallOption) (*ListContentRelationsResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.ListContentRelations(ctx, in, opts...)
}

func (m *defaultContent) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.CreateTag(ctx, in, opts...)
}

func (m *defaultContent) UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*UpdateTagResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.UpdateTag(ctx, in, opts...)
}

func (m *defaultContent) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.DeleteTag(ctx, in, opts...)
}

func (m *defaultContent) ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.ListTags(ctx, in, opts...)
}

func (m *defaultContent) ListPublicContents(ctx context.Context, in *ListPublicContentsRequest, opts ...grpc.CallOption) (*ListPublicContentsResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.ListPublicContents(ctx, in, opts...)
}

func (m *defaultContent) GetPublicContentBySlug(ctx context.Context, in *GetPublicContentBySlugRequest, opts ...grpc.CallOption) (*GetPublicContentBySlugResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.GetPublicContentBySlug(ctx, in, opts...)
}

func (m *defaultContent) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
