// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: v3/proto/file.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetVisibility int32

const (
	AssetVisibility_ASSET_VISIBILITY_UNSPECIFIED AssetVisibility = 0
	AssetVisibility_ASSET_VISIBILITY_PUBLIC      AssetVisibility = 1
	AssetVisibility_ASSET_VISIBILITY_PRIVATE     AssetVisibility = 2
)

// Enum value maps for AssetVisibility.
var (
	AssetVisibility_name = map[int32]string{
		0: "ASSET_VISIBILITY_UNSPECIFIED",
		1: "ASSET_VISIBILITY_PUBLIC",
		2: "ASSET_VISIBILITY_PRIVATE",
	}
	AssetVisibility_value = map[string]int32{
		"ASSET_VISIBILITY_UNSPECIFIED": 0,
		"ASSET_VISIBILITY_PUBLIC":      1,
		"ASSET_VISIBILITY_PRIVATE":     2,
	}
)

func (x AssetVisibility) Enum() *AssetVisibility {
	p := new(AssetVisibility)
	*p = x
	return p
}

func (x AssetVisibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetVisibility) Descriptor() protoreflect.EnumDescriptor {
	return file_v3_proto_file_proto_enumTypes[0].Descriptor()
}

func (AssetVisibility) Type() protoreflect.EnumType {
	return &file_v3_proto_file_proto_enumTypes[0]
}

func (x AssetVisibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetVisibility.Descriptor instead.
func (AssetVisibility) EnumDescriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{0}
}

type AssetStatus int32

const (
	AssetStatus_ASSET_STATUS_UNSPECIFIED AssetStatus = 0
	AssetStatus_ASSET_STATUS_PENDING     AssetStatus = 1
	AssetStatus_ASSET_STATUS_UPLOADED    AssetStatus = 2
	AssetStatus_ASSET_STATUS_DELETED     AssetStatus = 3
)

// Enum value maps for AssetStatus.
var (
	AssetStatus_name = map[int32]string{
		0: "ASSET_STATUS_UNSPECIFIED",
		1: "ASSET_STATUS_PENDING",
		2: "ASSET_STATUS_UPLOADED",
		3: "ASSET_STATUS_DELETED",
	}
	AssetStatus_value = map[string]int32{
		"ASSET_STATUS_UNSPECIFIED": 0,
		"ASSET_STATUS_PENDING":     1,
		"ASSET_STATUS_UPLOADED":    2,
		"ASSET_STATUS_DELETED":     3,
	}
)

func (x AssetStatus) Enum() *AssetStatus {
	p := new(AssetStatus)
	*p = x
	return p
}

func (x AssetStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v3_proto_file_proto_enumTypes[1].Descriptor()
}

func (AssetStatus) Type() protoreflect.EnumType {
	return &file_v3_proto_file_proto_enumTypes[1]
}

func (x AssetStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetStatus.Descriptor instead.
func (AssetStatus) EnumDescriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{1}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_v3_proto_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_v3_proto_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PingResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	UploadId      string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	OwnerUserId   string                 `protobuf:"bytes,3,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	CategoryKey   string                 `protobuf:"bytes,4,opt,name=category_key,json=categoryKey,proto3" json:"category_key,omitempty"`
	Visibility    AssetVisibility        `protobuf:"varint,5,opt,name=visibility,proto3,enum=file.AssetVisibility" json:"visibility,omitempty"`
	Status        AssetStatus            `protobuf:"varint,6,opt,name=status,proto3,enum=file.AssetStatus" json:"status,omitempty"`
	Bucket        string                 `protobuf:"bytes,7,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,8,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	PublicUrl     string                 `protobuf:"bytes,9,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	FileName      string                 `protobuf:"bytes,10,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,11,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ByteSize      int64                  `protobuf:"varint,12,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,14,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	UploadedAt    int64                  `protobuf:"varint,15,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	DeletedAt     int64                  `protobuf:"varint,16,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_v3_proto_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{2}
}

func (x *Asset) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *Asset) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *Asset) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *Asset) GetCategoryKey() string {
	if x != nil {
		return x.CategoryKey
	}
	return ""
}

func (x *Asset) GetVisibility() AssetVisibility {
	if x != nil {
		return x.Visibility
	}
	return AssetVisibility_ASSET_VISIBILITY_UNSPECIFIED
}

func (x *Asset) GetStatus() AssetStatus {
	if x != nil {
		return x.Status
	}
	return AssetStatus_ASSET_STATUS_UNSPECIFIED
}

func (x *Asset) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *Asset) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *Asset) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *Asset) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Asset) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Asset) GetByteSize() int64 {
	if x != nil {
		return x.ByteSize
	}
	return 0
}

func (x *Asset) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Asset) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *Asset) GetUploadedAt() int64 {
	if x != nil {
		return x.UploadedAt
	}
	return 0
}

func (x *Asset) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

type CreateUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId   string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	CategoryKey   string                 `protobuf:"bytes,2,opt,name=category_key,json=categoryKey,proto3" json:"category_key,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ByteSize      int64                  `protobuf:"varint,5,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	Visibility    AssetVisibility        `protobuf:"varint,6,opt,name=visibility,proto3,enum=file.AssetVisibility" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadRequest) Reset() {
	*x = CreateUploadRequest{}
	mi := &file_v3_proto_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadRequest) ProtoMessage() {}

func (x *CreateUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadRequest.ProtoReflect.Descriptor instead.
func (*CreateUploadRequest) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUploadRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *CreateUploadRequest) GetCategoryKey() string {
	if x != nil {
		return x.CategoryKey
	}
	return ""
}

func (x *CreateUploadRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *CreateUploadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CreateUploadRequest) GetByteSize() int64 {
	if x != nil {
		return x.ByteSize
	}
	return 0
}

func (x *CreateUploadRequest) GetVisibility() AssetVisibility {
	if x != nil {
		return x.Visibility
	}
	return AssetVisibility_ASSET_VISIBILITY_UNSPECIFIED
}

type CreateUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	MaxBytes      int64                  `protobuf:"varint,5,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadResponse) Reset() {
	*x = CreateUploadResponse{}
	mi := &file_v3_proto_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadResponse) ProtoMessage() {}

func (x *CreateUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadResponse.ProtoReflect.Descriptor instead.
func (*CreateUploadResponse) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUploadResponse) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *CreateUploadResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *CreateUploadResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CreateUploadResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *CreateUploadResponse) GetMaxBytes() int64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type CompleteUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId   string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	UploadId      string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUploadRequest) Reset() {
	*x = CompleteUploadRequest{}
	mi := &file_v3_proto_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadRequest) ProtoMessage() {}

func (x *CompleteUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadRequest.ProtoReflect.Descriptor instead.
func (*CompleteUploadRequest) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteUploadRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *CompleteUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type ListAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId   string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	CategoryKey   string                 `protobuf:"bytes,2,opt,name=category_key,json=categoryKey,proto3" json:"category_key,omitempty"`
	Status        AssetStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=file.AssetStatus" json:"status,omitempty"`
	Visibility    AssetVisibility        `protobuf:"varint,4,opt,name=visibility,proto3,enum=file.AssetVisibility" json:"visibility,omitempty"`
	OwnerUserId   string                 `protobuf:"bytes,5,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	Keyword       string                 `protobuf:"bytes,6,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Page          int32                  `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,8,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsRequest) Reset() {
	*x = ListAssetsRequest{}
	mi := &file_v3_proto_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsRequest) ProtoMessage() {}

func (x *ListAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsRequest.ProtoReflect.Descriptor instead.
func (*ListAssetsRequest) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{6}
}

func (x *ListAssetsRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *ListAssetsRequest) GetCategoryKey() string {
	if x != nil {
		return x.CategoryKey
	}
	return ""
}

func (x *ListAssetsRequest) GetStatus() AssetStatus {
	if x != nil {
		return x.Status
	}
	return AssetStatus_ASSET_STATUS_UNSPECIFIED
}

func (x *ListAssetsRequest) GetVisibility() AssetVisibility {
	if x != nil {
		return x.Visibility
	}
	return AssetVisibility_ASSET_VISIBILITY_UNSPECIFIED
}

func (x *ListAssetsRequest) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *ListAssetsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListAssetsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAssetsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId   string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetRequest) Reset() {
	*x = GetAssetRequest{}
	mi := &file_v3_proto_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetRequest) ProtoMessage() {}

func (x *GetAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetRequest.ProtoReflect.Descriptor instead.
func (*GetAssetRequest) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{7}
}

func (x *GetAssetRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *GetAssetRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

type AssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetResponse) Reset() {
	*x = AssetResponse{}
	mi := &file_v3_proto_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetResponse) ProtoMessage() {}

func (x *AssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetResponse.ProtoReflect.Descriptor instead.
func (*AssetResponse) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{8}
}

func (x *AssetResponse) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type ListAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Asset               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsResponse) Reset() {
	*x = ListAssetsResponse{}
	mi := &file_v3_proto_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsResponse) ProtoMessage() {}

func (x *ListAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsResponse.ProtoReflect.Descriptor instead.
func (*ListAssetsResponse) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{9}
}

func (x *ListAssetsResponse) GetItems() []*Asset {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListAssetsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListAssetsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAssetsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type DeleteAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId   string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssetRequest) Reset() {
	*x = DeleteAssetRequest{}
	mi := &file_v3_proto_file_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssetRequest) ProtoMessage() {}

func (x *DeleteAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssetRequest.ProtoReflect.Descriptor instead.
func (*DeleteAssetRequest) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAssetRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *DeleteAssetRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

type DeleteAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssetResponse) Reset() {
	*x = DeleteAssetResponse{}
	mi := &file_v3_proto_file_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssetResponse) ProtoMessage() {}

func (x *DeleteAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssetResponse.ProtoReflect.Descriptor instead.
func (*DeleteAssetResponse) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAssetResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type FileConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MaxUploadBytes    int64                  `protobuf:"varint,1,opt,name=max_upload_bytes,json=maxUploadBytes,proto3" json:"max_upload_bytes,omitempty"`
	PresignTtlSeconds int32                  `protobuf:"varint,2,opt,name=presign_ttl_seconds,json=presignTtlSeconds,proto3" json:"presign_ttl_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FileConfig) Reset() {
	*x = FileConfig{}
	mi := &file_v3_proto_file_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileConfig) ProtoMessage() {}

func (x *FileConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileConfig.ProtoReflect.Descriptor instead.
func (*FileConfig) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{12}
}

func (x *FileConfig) GetMaxUploadBytes() int64 {
	if x != nil {
		return x.MaxUploadBytes
	}
	return 0
}

func (x *FileConfig) GetPresignTtlSeconds() int32 {
	if x != nil {
		return x.PresignTtlSeconds
	}
	return 0
}

type GetFileConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileConfigRequest) Reset() {
	*x = GetFileConfigRequest{}
	mi := &file_v3_proto_file_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileConfigRequest) ProtoMessage() {}

func (x *GetFileConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileConfigRequest.ProtoReflect.Descriptor instead.
func (*GetFileConfigRequest) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{13}
}

type GetFileConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *FileConfig            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileConfigResponse) Reset() {
	*x = GetFileConfigResponse{}
	mi := &file_v3_proto_file_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileConfigResponse) ProtoMessage() {}

func (x *GetFileConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileConfigResponse.ProtoReflect.Descriptor instead.
func (*GetFileConfigResponse) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{14}
}

func (x *GetFileConfigResponse) GetConfig() *FileConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateFileConfigRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MaxUploadBytes    int64                  `protobuf:"varint,1,opt,name=max_upload_bytes,json=maxUploadBytes,proto3" json:"max_upload_bytes,omitempty"`
	PresignTtlSeconds int32                  `protobuf:"varint,2,opt,name=presign_ttl_seconds,json=presignTtlSeconds,proto3" json:"presign_ttl_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateFileConfigRequest) Reset() {
	*x = UpdateFileConfigRequest{}
	mi := &file_v3_proto_file_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFileConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileConfigRequest) ProtoMessage() {}

func (x *UpdateFileConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateFileConfigRequest) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateFileConfigRequest) GetMaxUploadBytes() int64 {
	if x != nil {
		return x.MaxUploadBytes
	}
	return 0
}

func (x *UpdateFileConfigRequest) GetPresignTtlSeconds() int32 {
	if x != nil {
		return x.PresignTtlSeconds
	}
	return 0
}

type UpdateFileConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *FileConfig            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFileConfigResponse) Reset() {
	*x = UpdateFileConfigResponse{}
	mi := &file_v3_proto_file_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFileConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileConfigResponse) ProtoMessage() {}

func (x *UpdateFileConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateFileConfigResponse) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateFileConfigResponse) GetConfig() *FileConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type FileCategory struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CategoryKey       string                 `protobuf:"bytes,1,opt,name=category_key,json=categoryKey,proto3" json:"category_key,omitempty"`
	DisplayName       string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Enabled           bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	IsDefault         bool                   `protobuf:"varint,5,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	SortOrder         int32                  `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	AllowedExtensions []string               `protobuf:"bytes,7,rep,name=allowed_extensions,json=allowedExtensions,proto3" json:"allowed_extensions,omitempty"`
	CreatedAt         int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FileCategory) Reset() {
	*x = FileCategory{}
	mi := &file_v3_proto_file_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCategory) ProtoMessage() {}

func (x *FileCategory) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCategory.ProtoReflect.Descriptor instead.
func (*FileCategory) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{17}
}

func (x *FileCategory) GetCategoryKey() string {
	if x != nil {
		return x.CategoryKey
	}
	return ""
}

func (x *FileCategory) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *FileCategory) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FileCategory) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FileCategory) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *FileCategory) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *FileCategory) GetAllowedExtensions() []string {
	if x != nil {
		return x.AllowedExtensions
	}
	return nil
}

func (x *FileCategory) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FileCategory) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ListFileCategoriesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeDisabled bool                   `protobuf:"varint,1,opt,name=include_disabled,json=includeDisabled,proto3" json:"include_disabled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListFileCategoriesRequest) Reset() {
	*x = ListFileCategoriesRequest{}
	mi := &file_v3_proto_file_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFileCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFileCategoriesRequest) ProtoMessage() {}

func (x *ListFileCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFileCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListFileCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{18}
}

func (x *ListFileCategoriesRequest) GetIncludeDisabled() bool {
	if x != nil {
		return x.IncludeDisabled
	}
	return false
}

type ListFileCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FileCategory        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFileCategoriesResponse) Reset() {
	*x = ListFileCategoriesResponse{}
	mi := &file_v3_proto_file_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFileCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFileCategoriesResponse) ProtoMessage() {}

func (x *ListFileCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFileCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListFileCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{19}
}

func (x *ListFileCategoriesResponse) GetItems() []*FileCategory {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateFileCategoryRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CategoryKey       string                 `protobuf:"bytes,1,opt,name=category_key,json=categoryKey,proto3" json:"category_key,omitempty"`
	DisplayName       string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Enabled           bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	IsDefault         bool                   `protobuf:"varint,5,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	SortOrder         int32                  `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	AllowedExtensions []string               `protobuf:"bytes,7,rep,name=allowed_extensions,json=allowedExtensions,proto3" json:"allowed_extensions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateFileCategoryRequest) Reset() {
	*x = CreateFileCategoryRequest{}
	mi := &file_v3_proto_file_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileCategoryRequest) ProtoMessage() {}

func (x *CreateFileCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateFileCategoryRequest) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{20}
}

func (x *CreateFileCategoryRequest) GetCategoryKey() string {
	if x != nil {
		return x.CategoryKey
	}
	return ""
}

func (x *CreateFileCategoryRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateFileCategoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateFileCategoryRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CreateFileCategoryRequest) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *CreateFileCategoryRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *CreateFileCategoryRequest) GetAllowedExtensions() []string {
	if x != nil {
		return x.AllowedExtensions
	}
	return nil
}

type UpdateFileCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryKey   string                 `protobuf:"bytes,1,opt,name=category_key,json=categoryKey,proto3" json:"category_key,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	SortOrder     int32                  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFileCategoryRequest) Reset() {
	*x = UpdateFileCategoryRequest{}
	mi := &file_v3_proto_file_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFileCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileCategoryRequest) ProtoMessage() {}

func (x *UpdateFileCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateFileCategoryRequest) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateFileCategoryRequest) GetCategoryKey() string {
	if x != nil {
		return x.CategoryKey
	}
	return ""
}

func (x *UpdateFileCategoryRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpdateFileCategoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateFileCategoryRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UpdateFileCategoryRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type UpdateFileCategoryExtensionsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CategoryKey       string                 `protobuf:"bytes,1,opt,name=category_key,json=categoryKey,proto3" json:"category_key,omitempty"`
	AllowedExtensions []string               `protobuf:"bytes,2,rep,name=allowed_extensions,json=allowedExtensions,proto3" json:"allowed_extensions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateFileCategoryExtensionsRequest) Reset() {
	*x = UpdateFileCategoryExtensionsRequest{}
	mi := &file_v3_proto_file_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFileCategoryExtensionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileCategoryExtensionsRequest) ProtoMessage() {}

func (x *UpdateFileCategoryExtensionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileCategoryExtensionsRequest.ProtoReflect.Descriptor instead.
func (*UpdateFileCategoryExtensionsRequest) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateFileCategoryExtensionsRequest) GetCategoryKey() string {
	if x != nil {
		return x.CategoryKey
	}
	return ""
}

func (x *UpdateFileCategoryExtensionsRequest) GetAllowedExtensions() []string {
	if x != nil {
		return x.AllowedExtensions
	}
	return nil
}

type SetDefaultFileCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryKey   string                 `protobuf:"bytes,1,opt,name=category_key,json=categoryKey,proto3" json:"category_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDefaultFileCategoryRequest) Reset() {
	*x = SetDefaultFileCategoryRequest{}
	mi := &file_v3_proto_file_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultFileCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultFileCategoryRequest) ProtoMessage() {}

func (x *SetDefaultFileCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultFileCategoryRequest.ProtoReflect.Descriptor instead.
func (*SetDefaultFileCategoryRequest) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{23}
}

func (x *SetDefaultFileCategoryRequest) GetCategoryKey() string {
	if x != nil {
		return x.CategoryKey
	}
	return ""
}

type FileCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *FileCategory          `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileCategoryResponse) Reset() {
	*x = FileCategoryResponse{}
	mi := &file_v3_proto_file_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCategoryResponse) ProtoMessage() {}

func (x *FileCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v3_proto_file_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCategoryResponse.ProtoReflect.Descriptor instead.
func (*FileCategoryResponse) Descriptor() ([]byte, []int) {
	return file_v3_proto_file_proto_rawDescGZIP(), []int{24}
}

func (x *FileCategoryResponse) GetCategory() *FileCategory {
	if x != nil {
		return x.Category
	}
	return nil
}

var File_v3_proto_file_proto protoreflect.FileDescriptor

const file_v3_proto_file_proto_rawDesc = "" +
	"\n" +
	"\x13v3/proto/file.proto\x12\x04file\"\r\n" +
	"\vPingRequest\"8\n" +
	"\fPingResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\"\x99\x04\n" +
	"\x05Asset\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\x12\"\n" +
	"\rowner_user_id\x18\x03 \x01(\tR\vownerUserId\x12!\n" +
	"\fcategory_key\x18\x04 \x01(\tR\vcategoryKey\x125\n" +
	"\n" +
	"visibility\x18\x05 \x01(\x0e2\x15.file.AssetVisibilityR\n" +
	"visibility\x12)\n" +
	"\x06status\x18\x06 \x01(\x0e2\x11.file.AssetStatusR\x06status\x12\x16\n" +
	"\x06bucket\x18\a \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"object_key\x18\b \x01(\tR\tobjectKey\x12\x1d\n" +
	"\n" +
	"public_url\x18\t \x01(\tR\tpublicUrl\x12\x1b\n" +
	"\tfile_name\x18\n" +
	" \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\v \x01(\tR\vcontentType\x12\x1b\n" +
	"\tbyte_size\x18\f \x01(\x03R\bbyteSize\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x0e \x01(\x03R\texpiresAt\x12\x1f\n" +
	"\vuploaded_at\x18\x0f \x01(\x03R\n" +
	"uploadedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\x10 \x01(\x03R\tdeletedAt\"\xf0\x01\n" +
	"\x13CreateUploadRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12!\n" +
	"\fcategory_key\x18\x02 \x01(\tR\vcategoryKey\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tbyte_size\x18\x05 \x01(\x03R\bbyteSize\x125\n" +
	"\n" +
	"visibility\x18\x06 \x01(\x0e2\x15.file.AssetVisibilityR\n" +
	"visibility\"\x93\x02\n" +
	"\x14CreateUploadResponse\x12!\n" +
	"\x05asset\x18\x01 \x01(\v2\v.file.AssetR\x05asset\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12A\n" +
	"\aheaders\x18\x03 \x03(\v2'.file.CreateUploadResponse.HeadersEntryR\aheaders\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\x12\x1b\n" +
	"\tmax_bytes\x18\x05 \x01(\x03R\bmaxBytes\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"X\n" +
	"\x15CompleteUploadRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\"\xab\x02\n" +
	"\x11ListAssetsRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12!\n" +
	"\fcategory_key\x18\x02 \x01(\tR\vcategoryKey\x12)\n" +
	"\x06status\x18\x03 \x01(\x0e2\x11.file.AssetStatusR\x06status\x125\n" +
	"\n" +
	"visibility\x18\x04 \x01(\x0e2\x15.file.AssetVisibilityR\n" +
	"visibility\x12\"\n" +
	"\rowner_user_id\x18\x05 \x01(\tR\vownerUserId\x12\x18\n" +
	"\akeyword\x18\x06 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\a \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\b \x01(\x05R\bpageSize\"P\n" +
	"\x0fGetAssetRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\"2\n" +
	"\rAssetResponse\x12!\n" +
	"\x05asset\x18\x01 \x01(\v2\v.file.AssetR\x05asset\"~\n" +
	"\x12ListAssetsResponse\x12!\n" +
	"\x05items\x18\x01 \x03(\v2\v.file.AssetR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"S\n" +
	"\x12DeleteAssetRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\"%\n" +
	"\x13DeleteAssetResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"f\n" +
	"\n" +
	"FileConfig\x12(\n" +
	"\x10max_upload_bytes\x18\x01 \x01(\x03R\x0emaxUploadBytes\x12.\n" +
	"\x13presign_ttl_seconds\x18\x02 \x01(\x05R\x11presignTtlSeconds\"\x16\n" +
	"\x14GetFileConfigRequest\"A\n" +
	"\x15GetFileConfigResponse\x12(\n" +
	"\x06config\x18\x01 \x01(\v2\x10.file.FileConfigR\x06config\"s\n" +
	"\x17UpdateFileConfigRequest\x12(\n" +
	"\x10max_upload_bytes\x18\x01 \x01(\x03R\x0emaxUploadBytes\x12.\n" +
	"\x13presign_ttl_seconds\x18\x02 \x01(\x05R\x11presignTtlSeconds\"D\n" +
	"\x18UpdateFileConfigResponse\x12(\n" +
	"\x06config\x18\x01 \x01(\v2\x10.file.FileConfigR\x06config\"\xbb\x02\n" +
	"\fFileCategory\x12!\n" +
	"\fcategory_key\x18\x01 \x01(\tR\vcategoryKey\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"is_default\x18\x05 \x01(\bR\tisDefault\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x05R\tsortOrder\x12-\n" +
	"\x12allowed_extensions\x18\a \x03(\tR\x11allowedExtensions\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"F\n" +
	"\x19ListFileCategoriesRequest\x12)\n" +
	"\x10include_disabled\x18\x01 \x01(\bR\x0fincludeDisabled\"F\n" +
	"\x1aListFileCategoriesResponse\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.file.FileCategoryR\x05items\"\x8a\x02\n" +
	"\x19CreateFileCategoryRequest\x12!\n" +
	"\fcategory_key\x18\x01 \x01(\tR\vcategoryKey\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"is_default\x18\x05 \x01(\bR\tisDefault\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x05R\tsortOrder\x12-\n" +
	"\x12allowed_extensions\x18\a \x03(\tR\x11allowedExtensions\"\xbc\x01\n" +
	"\x19UpdateFileCategoryRequest\x12!\n" +
	"\fcategory_key\x18\x01 \x01(\tR\vcategoryKey\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05R\tsortOrder\"w\n" +
	"#UpdateFileCategoryExtensionsRequest\x12!\n" +
	"\fcategory_key\x18\x01 \x01(\tR\vcategoryKey\x12-\n" +
	"\x12allowed_extensions\x18\x02 \x03(\tR\x11allowedExtensions\"B\n" +
	"\x1dSetDefaultFileCategoryRequest\x12!\n" +
	"\fcategory_key\x18\x01 \x01(\tR\vcategoryKey\"F\n" +
	"\x14FileCategoryResponse\x12.\n" +
	"\bcategory\x18\x01 \x01(\v2\x12.file.FileCategoryR\bcategory*n\n" +
	"\x0fAssetVisibility\x12 \n" +
	"\x1cASSET_VISIBILITY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ASSET_VISIBILITY_PUBLIC\x10\x01\x12\x1c\n" +
	"\x18ASSET_VISIBILITY_PRIVATE\x10\x02*z\n" +
	"\vAssetStatus\x12\x1c\n" +
	"\x18ASSET_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ASSET_STATUS_PENDING\x10\x01\x12\x19\n" +
	"\x15ASSET_STATUS_UPLOADED\x10\x02\x12\x18\n" +
	"\x14ASSET_STATUS_DELETED\x10\x032\xe2\a\n" +
	"\vFileService\x12-\n" +
	"\x04Ping\x12\x11.file.PingRequest\x1a\x12.file.PingResponse\x12E\n" +
	"\fCreateUpload\x12\x19.file.CreateUploadRequest\x1a\x1a.file.CreateUploadResponse\x12B\n" +
	"\x0eCompleteUpload\x12\x1b.file.CompleteUploadRequest\x1a\x13.file.AssetResponse\x12?\n" +
	"\n" +
	"ListAssets\x12\x17.file.ListAssetsRequest\x1a\x18.file.ListAssetsResponse\x126\n" +
	"\bGetAsset\x12\x15.file.GetAssetRequest\x1a\x13.file.AssetResponse\x12B\n" +
	"\vDeleteAsset\x12\x18.file.DeleteAssetRequest\x1a\x19.file.DeleteAssetResponse\x12H\n" +
	"\rGetFileConfig\x12\x1a.file.GetFileConfigRequest\x1a\x1b.file.GetFileConfigResponse\x12Q\n" +
	"\x10UpdateFileConfig\x12\x1d.file.UpdateFileConfigRequest\x1a\x1e.file.UpdateFileConfigResponse\x12W\n" +
	"\x12ListFileCategories\x12\x1f.file.ListFileCategoriesRequest\x1a .file.ListFileCategoriesResponse\x12Q\n" +
	"\x12CreateFileCategory\x12\x1f.file.CreateFileCategoryRequest\x1a\x1a.file.FileCategoryResponse\x12Q\n" +
	"\x12UpdateFileCategory\x12\x1f.file.UpdateFileCategoryRequest\x1a\x1a.file.FileCategoryResponse\x12e\n" +
	"\x1cUpdateFileCategoryExtensions\x12).file.UpdateFileCategoryExtensionsRequest\x1a\x1a.file.FileCategoryResponse\x12Y\n" +
	"\x16SetDefaultFileCategory\x12#.file.SetDefaultFileCategoryRequest\x1a\x1a.file.FileCategoryResponseB\x12Z\x10services/file/pbb\x06proto3"

var (
	file_v3_proto_file_proto_rawDescOnce sync.Once
	file_v3_proto_file_proto_rawDescData []byte
)

func file_v3_proto_file_proto_rawDescGZIP() []byte {
	file_v3_proto_file_proto_rawDescOnce.Do(func() {
		file_v3_proto_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v3_proto_file_proto_rawDesc), len(file_v3_proto_file_proto_rawDesc)))
	})
	return file_v3_proto_file_proto_rawDescData
}

var file_v3_proto_file_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v3_proto_file_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_v3_proto_file_proto_goTypes = []any{
	(AssetVisibility)(0),                        // 0: file.AssetVisibility
	(AssetStatus)(0),                            // 1: file.AssetStatus
	(*PingRequest)(nil),                         // 2: file.PingRequest
	(*PingResponse)(nil),                        // 3: file.PingResponse
	(*Asset)(nil),                               // 4: file.Asset
	(*CreateUploadRequest)(nil),                 // 5: file.CreateUploadRequest
	(*CreateUploadResponse)(nil),                // 6: file.CreateUploadResponse
	(*CompleteUploadRequest)(nil),               // 7: file.CompleteUploadRequest
	(*ListAssetsRequest)(nil),                   // 8: file.ListAssetsRequest
	(*GetAssetRequest)(nil),                     // 9: file.GetAssetRequest
	(*AssetResponse)(nil),                       // 10: file.AssetResponse
	(*ListAssetsResponse)(nil),                  // 11: file.ListAssetsResponse
	(*DeleteAssetRequest)(nil),                  // 12: file.DeleteAssetRequest
	(*DeleteAssetResponse)(nil),                 // 13: file.DeleteAssetResponse
	(*FileConfig)(nil),                          // 14: file.FileConfig
	(*GetFileConfigRequest)(nil),                // 15: file.GetFileConfigRequest
	(*GetFileConfigResponse)(nil),               // 16: file.GetFileConfigResponse
	(*UpdateFileConfigRequest)(nil),             // 17: file.UpdateFileConfigRequest
	(*UpdateFileConfigResponse)(nil),            // 18: file.UpdateFileConfigResponse
	(*FileCategory)(nil),                        // 19: file.FileCategory
	(*ListFileCategoriesRequest)(nil),           // 20: file.ListFileCategoriesRequest
	(*ListFileCategoriesResponse)(nil),          // 21: file.ListFileCategoriesResponse
	(*CreateFileCategoryRequest)(nil),           // 22: file.CreateFileCategoryRequest
	(*UpdateFileCategoryRequest)(nil),           // 23: file.UpdateFileCategoryRequest
	(*UpdateFileCategoryExtensionsRequest)(nil), // 24: file.UpdateFileCategoryExtensionsRequest
	(*SetDefaultFileCategoryRequest)(nil),       // 25: file.SetDefaultFileCategoryRequest
	(*FileCategoryResponse)(nil),                // 26: file.FileCategoryResponse
	nil,                                         // 27: file.CreateUploadResponse.HeadersEntry
}
var file_v3_proto_file_proto_depIdxs = []int32{
	0,  // 0: file.Asset.visibility:type_name -> file.AssetVisibility
	1,  // 1: file.Asset.status:type_name -> file.AssetStatus
	0,  // 2: file.CreateUploadRequest.visibility:type_name -> file.AssetVisibility
	4,  // 3: file.CreateUploadResponse.asset:type_name -> file.Asset
	27, // 4: file.CreateUploadResponse.headers:type_name -> file.CreateUploadResponse.HeadersEntry
	1,  // 5: file.ListAssetsRequest.status:type_name -> file.AssetStatus
	0,  // 6: file.ListAssetsRequest.visibility:type_name -> file.AssetVisibility
	4,  // 7: file.AssetResponse.asset:type_name -> file.Asset
	4,  // 8: file.ListAssetsResponse.items:type_name -> file.Asset
	14, // 9: file.GetFileConfigResponse.config:type_name -> file.FileConfig
	14, // 10: file.UpdateFileConfigResponse.config:type_name -> file.FileConfig
	19, // 11: file.ListFileCategoriesResponse.items:type_name -> file.FileCategory
	19, // 12: file.FileCategoryResponse.category:type_name -> file.FileCategory
	2,  // 13: file.FileService.Ping:input_type -> file.PingRequest
	5,  // 14: file.FileService.CreateUpload:input_type -> file.CreateUploadRequest
	7,  // 15: file.FileService.CompleteUpload:input_type -> file.CompleteUploadRequest
	8,  // 16: file.FileService.ListAssets:input_type -> file.ListAssetsRequest
	9,  // 17: file.FileService.GetAsset:input_type -> file.GetAssetRequest
	12, // 18: file.FileService.DeleteAsset:input_type -> file.DeleteAssetRequest
	15, // 19: file.FileService.GetFileConfig:input_type -> file.GetFileConfigRequest
	17, // 20: file.FileService.UpdateFileConfig:input_type -> file.UpdateFileConfigRequest
	20, // 21: file.FileService.ListFileCategories:input_type -> file.ListFileCategoriesRequest
	22, // 22: file.FileService.CreateFileCategory:input_type -> file.CreateFileCategoryRequest
	23, // 23: file.FileService.UpdateFileCategory:input_type -> file.UpdateFileCategoryRequest
	24, // 24: file.FileService.UpdateFileCategoryExtensions:input_type -> file.UpdateFileCategoryExtensionsRequest
	25, // 25: file.FileService.SetDefaultFileCategory:input_type -> file.SetDefaultFileCategoryRequest
	3,  // 26: file.FileService.Ping:output_type -> file.PingResponse
	6,  // 27: file.FileService.CreateUpload:output_type -> file.CreateUploadResponse
	10, // 28: file.FileService.CompleteUpload:output_type -> file.AssetResponse
	11, // 29: file.FileService.ListAssets:output_type -> file.ListAssetsResponse
	10, // 30: file.FileService.GetAsset:output_type -> file.AssetResponse
	13, // 31: file.FileService.DeleteAsset:output_type -> file.DeleteAssetResponse
	16, // 32: file.FileService.GetFileConfig:output_type -> file.GetFileConfigResponse
	18, // 33: file.FileService.UpdateFileConfig:output_type -> file.UpdateFileConfigResponse
	21, // 34: file.FileService.ListFileCategories:output_type -> file.ListFileCategoriesResponse
	26, // 35: file.FileService.CreateFileCategory:output_type -> file.FileCategoryResponse
	26, // 36: file.FileService.UpdateFileCategory:output_type -> file.FileCategoryResponse
	26, // 37: file.FileService.UpdateFileCategoryExtensions:output_type -> file.FileCategoryResponse
	26, // 38: file.FileService.SetDefaultFileCategory:output_type -> file.FileCategoryResponse
	26, // [26:39] is the sub-list for method output_type
	13, // [13:26] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_v3_proto_file_proto_init() }
func file_v3_proto_file_proto_init() {
	if File_v3_proto_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v3_proto_file_proto_rawDesc), len(file_v3_proto_file_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v3_proto_file_proto_goTypes,
		DependencyIndexes: file_v3_proto_file_proto_depIdxs,
		EnumInfos:         file_v3_proto_file_proto_enumTypes,
		MessageInfos:      file_v3_proto_file_proto_msgTypes,
	}.Build()
	File_v3_proto_file_proto = out.File
	file_v3_proto_file_proto_goTypes = nil
	file_v3_proto_file_proto_depIdxs = nil
}
