// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: file.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileScope int32

const (
	FileScope_FILE_SCOPE_UNSPECIFIED   FileScope = 0
	FileScope_FILE_SCOPE_AVATAR        FileScope = 1
	FileScope_FILE_SCOPE_CONTENT_COVER FileScope = 2
	FileScope_FILE_SCOPE_CONTENT_IMAGE FileScope = 3
	FileScope_FILE_SCOPE_ATTACHMENT    FileScope = 4
)

// Enum value maps for FileScope.
var (
	FileScope_name = map[int32]string{
		0: "FILE_SCOPE_UNSPECIFIED",
		1: "FILE_SCOPE_AVATAR",
		2: "FILE_SCOPE_CONTENT_COVER",
		3: "FILE_SCOPE_CONTENT_IMAGE",
		4: "FILE_SCOPE_ATTACHMENT",
	}
	FileScope_value = map[string]int32{
		"FILE_SCOPE_UNSPECIFIED":   0,
		"FILE_SCOPE_AVATAR":        1,
		"FILE_SCOPE_CONTENT_COVER": 2,
		"FILE_SCOPE_CONTENT_IMAGE": 3,
		"FILE_SCOPE_ATTACHMENT":    4,
	}
)

func (x FileScope) Enum() *FileScope {
	p := new(FileScope)
	*p = x
	return p
}

func (x FileScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileScope) Descriptor() protoreflect.EnumDescriptor {
	return file_file_proto_enumTypes[0].Descriptor()
}

func (FileScope) Type() protoreflect.EnumType {
	return &file_file_proto_enumTypes[0]
}

func (x FileScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileScope.Descriptor instead.
func (FileScope) EnumDescriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{0}
}

type AssetVisibility int32

const (
	AssetVisibility_ASSET_VISIBILITY_UNSPECIFIED AssetVisibility = 0
	AssetVisibility_ASSET_VISIBILITY_PUBLIC      AssetVisibility = 1
	AssetVisibility_ASSET_VISIBILITY_PRIVATE     AssetVisibility = 2
)

// Enum value maps for AssetVisibility.
var (
	AssetVisibility_name = map[int32]string{
		0: "ASSET_VISIBILITY_UNSPECIFIED",
		1: "ASSET_VISIBILITY_PUBLIC",
		2: "ASSET_VISIBILITY_PRIVATE",
	}
	AssetVisibility_value = map[string]int32{
		"ASSET_VISIBILITY_UNSPECIFIED": 0,
		"ASSET_VISIBILITY_PUBLIC":      1,
		"ASSET_VISIBILITY_PRIVATE":     2,
	}
)

func (x AssetVisibility) Enum() *AssetVisibility {
	p := new(AssetVisibility)
	*p = x
	return p
}

func (x AssetVisibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetVisibility) Descriptor() protoreflect.EnumDescriptor {
	return file_file_proto_enumTypes[1].Descriptor()
}

func (AssetVisibility) Type() protoreflect.EnumType {
	return &file_file_proto_enumTypes[1]
}

func (x AssetVisibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetVisibility.Descriptor instead.
func (AssetVisibility) EnumDescriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{1}
}

type AssetStatus int32

const (
	AssetStatus_ASSET_STATUS_UNSPECIFIED AssetStatus = 0
	AssetStatus_ASSET_STATUS_PENDING     AssetStatus = 1
	AssetStatus_ASSET_STATUS_UPLOADED    AssetStatus = 2
	AssetStatus_ASSET_STATUS_DELETED     AssetStatus = 3
)

// Enum value maps for AssetStatus.
var (
	AssetStatus_name = map[int32]string{
		0: "ASSET_STATUS_UNSPECIFIED",
		1: "ASSET_STATUS_PENDING",
		2: "ASSET_STATUS_UPLOADED",
		3: "ASSET_STATUS_DELETED",
	}
	AssetStatus_value = map[string]int32{
		"ASSET_STATUS_UNSPECIFIED": 0,
		"ASSET_STATUS_PENDING":     1,
		"ASSET_STATUS_UPLOADED":    2,
		"ASSET_STATUS_DELETED":     3,
	}
)

func (x AssetStatus) Enum() *AssetStatus {
	p := new(AssetStatus)
	*p = x
	return p
}

func (x AssetStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_file_proto_enumTypes[2].Descriptor()
}

func (AssetStatus) Type() protoreflect.EnumType {
	return &file_file_proto_enumTypes[2]
}

func (x AssetStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetStatus.Descriptor instead.
func (AssetStatus) EnumDescriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{2}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PingResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	UploadId      string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	OwnerUserId   string                 `protobuf:"bytes,3,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	Scope         FileScope              `protobuf:"varint,4,opt,name=scope,proto3,enum=file.FileScope" json:"scope,omitempty"`
	Visibility    AssetVisibility        `protobuf:"varint,5,opt,name=visibility,proto3,enum=file.AssetVisibility" json:"visibility,omitempty"`
	Status        AssetStatus            `protobuf:"varint,6,opt,name=status,proto3,enum=file.AssetStatus" json:"status,omitempty"`
	Bucket        string                 `protobuf:"bytes,7,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,8,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	PublicUrl     string                 `protobuf:"bytes,9,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	FileName      string                 `protobuf:"bytes,10,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,11,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ByteSize      int64                  `protobuf:"varint,12,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,14,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	UploadedAt    int64                  `protobuf:"varint,15,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	DeletedAt     int64                  `protobuf:"varint,16,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{2}
}

func (x *Asset) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *Asset) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *Asset) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *Asset) GetScope() FileScope {
	if x != nil {
		return x.Scope
	}
	return FileScope_FILE_SCOPE_UNSPECIFIED
}

func (x *Asset) GetVisibility() AssetVisibility {
	if x != nil {
		return x.Visibility
	}
	return AssetVisibility_ASSET_VISIBILITY_UNSPECIFIED
}

func (x *Asset) GetStatus() AssetStatus {
	if x != nil {
		return x.Status
	}
	return AssetStatus_ASSET_STATUS_UNSPECIFIED
}

func (x *Asset) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *Asset) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *Asset) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *Asset) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Asset) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Asset) GetByteSize() int64 {
	if x != nil {
		return x.ByteSize
	}
	return 0
}

func (x *Asset) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Asset) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *Asset) GetUploadedAt() int64 {
	if x != nil {
		return x.UploadedAt
	}
	return 0
}

func (x *Asset) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

type CreateUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId   string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	Scope         FileScope              `protobuf:"varint,2,opt,name=scope,proto3,enum=file.FileScope" json:"scope,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ByteSize      int64                  `protobuf:"varint,5,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	Visibility    AssetVisibility        `protobuf:"varint,6,opt,name=visibility,proto3,enum=file.AssetVisibility" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadRequest) Reset() {
	*x = CreateUploadRequest{}
	mi := &file_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadRequest) ProtoMessage() {}

func (x *CreateUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadRequest.ProtoReflect.Descriptor instead.
func (*CreateUploadRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUploadRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *CreateUploadRequest) GetScope() FileScope {
	if x != nil {
		return x.Scope
	}
	return FileScope_FILE_SCOPE_UNSPECIFIED
}

func (x *CreateUploadRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *CreateUploadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CreateUploadRequest) GetByteSize() int64 {
	if x != nil {
		return x.ByteSize
	}
	return 0
}

func (x *CreateUploadRequest) GetVisibility() AssetVisibility {
	if x != nil {
		return x.Visibility
	}
	return AssetVisibility_ASSET_VISIBILITY_UNSPECIFIED
}

type CreateUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	MaxBytes      int64                  `protobuf:"varint,5,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadResponse) Reset() {
	*x = CreateUploadResponse{}
	mi := &file_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadResponse) ProtoMessage() {}

func (x *CreateUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadResponse.ProtoReflect.Descriptor instead.
func (*CreateUploadResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUploadResponse) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *CreateUploadResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *CreateUploadResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CreateUploadResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *CreateUploadResponse) GetMaxBytes() int64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type CompleteUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId   string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	UploadId      string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUploadRequest) Reset() {
	*x = CompleteUploadRequest{}
	mi := &file_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadRequest) ProtoMessage() {}

func (x *CompleteUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadRequest.ProtoReflect.Descriptor instead.
func (*CompleteUploadRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteUploadRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *CompleteUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type GetAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId   string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetRequest) Reset() {
	*x = GetAssetRequest{}
	mi := &file_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetRequest) ProtoMessage() {}

func (x *GetAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetRequest.ProtoReflect.Descriptor instead.
func (*GetAssetRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{6}
}

func (x *GetAssetRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *GetAssetRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

type AssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetResponse) Reset() {
	*x = AssetResponse{}
	mi := &file_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetResponse) ProtoMessage() {}

func (x *AssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetResponse.ProtoReflect.Descriptor instead.
func (*AssetResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{7}
}

func (x *AssetResponse) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type DeleteAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId   string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssetRequest) Reset() {
	*x = DeleteAssetRequest{}
	mi := &file_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssetRequest) ProtoMessage() {}

func (x *DeleteAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssetRequest.ProtoReflect.Descriptor instead.
func (*DeleteAssetRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAssetRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *DeleteAssetRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

type DeleteAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssetResponse) Reset() {
	*x = DeleteAssetResponse{}
	mi := &file_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssetResponse) ProtoMessage() {}

func (x *DeleteAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssetResponse.ProtoReflect.Descriptor instead.
func (*DeleteAssetResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAssetResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_file_proto protoreflect.FileDescriptor

const file_file_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"file.proto\x12\x04file\"\r\n" +
	"\vPingRequest\"8\n" +
	"\fPingResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\"\x9d\x04\n" +
	"\x05Asset\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\x12\"\n" +
	"\rowner_user_id\x18\x03 \x01(\tR\vownerUserId\x12%\n" +
	"\x05scope\x18\x04 \x01(\x0e2\x0f.file.FileScopeR\x05scope\x125\n" +
	"\n" +
	"visibility\x18\x05 \x01(\x0e2\x15.file.AssetVisibilityR\n" +
	"visibility\x12)\n" +
	"\x06status\x18\x06 \x01(\x0e2\x11.file.AssetStatusR\x06status\x12\x16\n" +
	"\x06bucket\x18\a \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"object_key\x18\b \x01(\tR\tobjectKey\x12\x1d\n" +
	"\n" +
	"public_url\x18\t \x01(\tR\tpublicUrl\x12\x1b\n" +
	"\tfile_name\x18\n" +
	" \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\v \x01(\tR\vcontentType\x12\x1b\n" +
	"\tbyte_size\x18\f \x01(\x03R\bbyteSize\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x0e \x01(\x03R\texpiresAt\x12\x1f\n" +
	"\vuploaded_at\x18\x0f \x01(\x03R\n" +
	"uploadedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\x10 \x01(\x03R\tdeletedAt\"\xf4\x01\n" +
	"\x13CreateUploadRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12%\n" +
	"\x05scope\x18\x02 \x01(\x0e2\x0f.file.FileScopeR\x05scope\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tbyte_size\x18\x05 \x01(\x03R\bbyteSize\x125\n" +
	"\n" +
	"visibility\x18\x06 \x01(\x0e2\x15.file.AssetVisibilityR\n" +
	"visibility\"\x93\x02\n" +
	"\x14CreateUploadResponse\x12!\n" +
	"\x05asset\x18\x01 \x01(\v2\v.file.AssetR\x05asset\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12A\n" +
	"\aheaders\x18\x03 \x03(\v2'.file.CreateUploadResponse.HeadersEntryR\aheaders\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\x12\x1b\n" +
	"\tmax_bytes\x18\x05 \x01(\x03R\bmaxBytes\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"X\n" +
	"\x15CompleteUploadRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\"P\n" +
	"\x0fGetAssetRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\"2\n" +
	"\rAssetResponse\x12!\n" +
	"\x05asset\x18\x01 \x01(\v2\v.file.AssetR\x05asset\"S\n" +
	"\x12DeleteAssetRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\"%\n" +
	"\x13DeleteAssetResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok*\x95\x01\n" +
	"\tFileScope\x12\x1a\n" +
	"\x16FILE_SCOPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11FILE_SCOPE_AVATAR\x10\x01\x12\x1c\n" +
	"\x18FILE_SCOPE_CONTENT_COVER\x10\x02\x12\x1c\n" +
	"\x18FILE_SCOPE_CONTENT_IMAGE\x10\x03\x12\x19\n" +
	"\x15FILE_SCOPE_ATTACHMENT\x10\x04*n\n" +
	"\x0fAssetVisibility\x12 \n" +
	"\x1cASSET_VISIBILITY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ASSET_VISIBILITY_PUBLIC\x10\x01\x12\x1c\n" +
	"\x18ASSET_VISIBILITY_PRIVATE\x10\x02*z\n" +
	"\vAssetStatus\x12\x1c\n" +
	"\x18ASSET_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ASSET_STATUS_PENDING\x10\x01\x12\x19\n" +
	"\x15ASSET_STATUS_UPLOADED\x10\x02\x12\x18\n" +
	"\x14ASSET_STATUS_DELETED\x10\x032\xc3\x02\n" +
	"\vFileService\x12-\n" +
	"\x04Ping\x12\x11.file.PingRequest\x1a\x12.file.PingResponse\x12E\n" +
	"\fCreateUpload\x12\x19.file.CreateUploadRequest\x1a\x1a.file.CreateUploadResponse\x12B\n" +
	"\x0eCompleteUpload\x12\x1b.file.CompleteUploadRequest\x1a\x13.file.AssetResponse\x126\n" +
	"\bGetAsset\x12\x15.file.GetAssetRequest\x1a\x13.file.AssetResponse\x12B\n" +
	"\vDeleteAsset\x12\x18.file.DeleteAssetRequest\x1a\x19.file.DeleteAssetResponseB\x12Z\x10services/file/pbb\x06proto3"

var (
	file_file_proto_rawDescOnce sync.Once
	file_file_proto_rawDescData []byte
)

func file_file_proto_rawDescGZIP() []byte {
	file_file_proto_rawDescOnce.Do(func() {
		file_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)))
	})
	return file_file_proto_rawDescData
}

var file_file_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_file_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_file_proto_goTypes = []any{
	(FileScope)(0),                // 0: file.FileScope
	(AssetVisibility)(0),          // 1: file.AssetVisibility
	(AssetStatus)(0),              // 2: file.AssetStatus
	(*PingRequest)(nil),           // 3: file.PingRequest
	(*PingResponse)(nil),          // 4: file.PingResponse
	(*Asset)(nil),                 // 5: file.Asset
	(*CreateUploadRequest)(nil),   // 6: file.CreateUploadRequest
	(*CreateUploadResponse)(nil),  // 7: file.CreateUploadResponse
	(*CompleteUploadRequest)(nil), // 8: file.CompleteUploadRequest
	(*GetAssetRequest)(nil),       // 9: file.GetAssetRequest
	(*AssetResponse)(nil),         // 10: file.AssetResponse
	(*DeleteAssetRequest)(nil),    // 11: file.DeleteAssetRequest
	(*DeleteAssetResponse)(nil),   // 12: file.DeleteAssetResponse
	nil,                           // 13: file.CreateUploadResponse.HeadersEntry
}
var file_file_proto_depIdxs = []int32{
	0,  // 0: file.Asset.scope:type_name -> file.FileScope
	1,  // 1: file.Asset.visibility:type_name -> file.AssetVisibility
	2,  // 2: file.Asset.status:type_name -> file.AssetStatus
	0,  // 3: file.CreateUploadRequest.scope:type_name -> file.FileScope
	1,  // 4: file.CreateUploadRequest.visibility:type_name -> file.AssetVisibility
	5,  // 5: file.CreateUploadResponse.asset:type_name -> file.Asset
	13, // 6: file.CreateUploadResponse.headers:type_name -> file.CreateUploadResponse.HeadersEntry
	5,  // 7: file.AssetResponse.asset:type_name -> file.Asset
	3,  // 8: file.FileService.Ping:input_type -> file.PingRequest
	6,  // 9: file.FileService.CreateUpload:input_type -> file.CreateUploadRequest
	8,  // 10: file.FileService.CompleteUpload:input_type -> file.CompleteUploadRequest
	9,  // 11: file.FileService.GetAsset:input_type -> file.GetAssetRequest
	11, // 12: file.FileService.DeleteAsset:input_type -> file.DeleteAssetRequest
	4,  // 13: file.FileService.Ping:output_type -> file.PingResponse
	7,  // 14: file.FileService.CreateUpload:output_type -> file.CreateUploadResponse
	10, // 15: file.FileService.CompleteUpload:output_type -> file.AssetResponse
	10, // 16: file.FileService.GetAsset:output_type -> file.AssetResponse
	12, // 17: file.FileService.DeleteAsset:output_type -> file.DeleteAssetResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_file_proto_init() }
func file_file_proto_init() {
	if File_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_proto_goTypes,
		DependencyIndexes: file_file_proto_depIdxs,
		EnumInfos:         file_file_proto_enumTypes,
		MessageInfos:      file_file_proto_msgTypes,
	}.Build()
	File_file_proto = out.File
	file_file_proto_goTypes = nil
	file_file_proto_depIdxs = nil
}
