// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	file "github.com/HappyLadySauce/Beehive-Blog-V3/services/file/internal/handler/file"
	"github.com/HappyLadySauce/Beehive-Blog-V3/services/file/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Read a public uploaded asset
				Method:  http.MethodGet,
				Path:    "/assets/:asset_id",
				Handler: file.FileAssetGetHandler(serverCtx),
			},
			{
				// Read public uploaded asset metadata
				Method:  http.MethodHead,
				Path:    "/assets/:asset_id",
				Handler: file.FileAssetHeadHandler(serverCtx),
			},
			{
				// Preflight public asset read
				Method:  http.MethodOptions,
				Path:    "/assets/:asset_id",
				Handler: file.FileAssetOptionsHandler(serverCtx),
			},
			{
				// Upload a pending local file object
				Method:  http.MethodPut,
				Path:    "/uploads/:upload_id",
				Handler: file.FileUploadPutHandler(serverCtx),
			},
			{
				// Preflight local file upload
				Method:  http.MethodOptions,
				Path:    "/uploads/:upload_id",
				Handler: file.FileUploadOptionsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/files"),
	)
}
