// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: identity.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive-Blog-V3/services/identity/internal/logic"
	"github.com/HappyLadySauce/Beehive-Blog-V3/services/identity/internal/svc"
	"github.com/HappyLadySauce/Beehive-Blog-V3/services/identity/pb"
)

type IdentityServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedIdentityServer
}

func NewIdentityServer(svcCtx *svc.ServiceContext) *IdentityServer {
	return &IdentityServer{
		svcCtx: svcCtx,
	}
}

func (s *IdentityServer) RegisterLocalUser(ctx context.Context, in *pb.RegisterLocalUserRequest) (*pb.RegisterLocalUserResponse, error) {
	l := logic.NewRegisterLocalUserLogic(ctx, s.svcCtx)
	return l.RegisterLocalUser(in)
}

func (s *IdentityServer) LoginLocalUser(ctx context.Context, in *pb.LoginLocalUserRequest) (*pb.LoginLocalUserResponse, error) {
	l := logic.NewLoginLocalUserLogic(ctx, s.svcCtx)
	return l.LoginLocalUser(in)
}

func (s *IdentityServer) StartSsoLogin(ctx context.Context, in *pb.StartSsoLoginRequest) (*pb.StartSsoLoginResponse, error) {
	l := logic.NewStartSsoLoginLogic(ctx, s.svcCtx)
	return l.StartSsoLogin(in)
}

func (s *IdentityServer) FinishSsoLogin(ctx context.Context, in *pb.FinishSsoLoginRequest) (*pb.FinishSsoLoginResponse, error) {
	l := logic.NewFinishSsoLoginLogic(ctx, s.svcCtx)
	return l.FinishSsoLogin(in)
}

func (s *IdentityServer) RefreshSessionToken(ctx context.Context, in *pb.RefreshSessionTokenRequest) (*pb.RefreshSessionTokenResponse, error) {
	l := logic.NewRefreshSessionTokenLogic(ctx, s.svcCtx)
	return l.RefreshSessionToken(in)
}

func (s *IdentityServer) LogoutSession(ctx context.Context, in *pb.LogoutSessionRequest) (*pb.LogoutSessionResponse, error) {
	l := logic.NewLogoutSessionLogic(ctx, s.svcCtx)
	return l.LogoutSession(in)
}

func (s *IdentityServer) GetCurrentUser(ctx context.Context, in *pb.GetCurrentUserRequest) (*pb.GetCurrentUserResponse, error) {
	l := logic.NewGetCurrentUserLogic(ctx, s.svcCtx)
	return l.GetCurrentUser(in)
}

func (s *IdentityServer) IntrospectAccessToken(ctx context.Context, in *pb.IntrospectAccessTokenRequest) (*pb.IntrospectAccessTokenResponse, error) {
	l := logic.NewIntrospectAccessTokenLogic(ctx, s.svcCtx)
	return l.IntrospectAccessToken(in)
}
