// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AuthLoginReq struct {
	LoginIdentifier string `json:"login_identifier" validate:"required,min=1,max=320"`
	Password        string `json:"password" validate:"required,min=1,max=128"`
	ClientType      string `json:"client_type,optional" validate:"omitempty,max=32"`
	DeviceId        string `json:"device_id,optional" validate:"omitempty,max=128"`
	DeviceName      string `json:"device_name,optional" validate:"omitempty,max=128"`
	UserAgent       string `json:"user_agent,optional" validate:"omitempty,max=512"`
}

type AuthLoginResp struct {
	AccessToken  string          `json:"access_token"`
	RefreshToken string          `json:"refresh_token"`
	ExpiresIn    int64           `json:"expires_in"`
	TokenType    string          `json:"token_type"`
	SessionId    string          `json:"session_id"`
	User         AuthUserProfile `json:"user"`
	Session      AuthSessionView `json:"session"`
}

type AuthLogoutReq struct {
	Authorization string `header:"Authorization" validate:"required"`
	RefreshToken  string `json:"refresh_token,optional" validate:"omitempty,max=4096"`
}

type AuthLogoutResp struct {
	Ok bool `json:"ok"`
}

type AuthMeReq struct {
	Authorization string `header:"Authorization" validate:"required"`
}

type AuthMeResp struct {
	User AuthUserProfile `json:"user"`
}

type AuthRefreshReq struct {
	RefreshToken string `json:"refresh_token" validate:"required,min=1,max=4096"`
	UserAgent    string `json:"user_agent,optional" validate:"omitempty,max=512"`
}

type AuthRefreshResp struct {
	AccessToken  string          `json:"access_token"`
	RefreshToken string          `json:"refresh_token"`
	ExpiresIn    int64           `json:"expires_in"`
	TokenType    string          `json:"token_type"`
	SessionId    string          `json:"session_id"`
	Session      AuthSessionView `json:"session"`
}

type AuthRegisterReq struct {
	Username string `json:"username" validate:"required,min=3,max=64"`
	Email    string `json:"email" validate:"required,email,max=320"`
	Password string `json:"password" validate:"required,min=8,max=128"`
	Nickname string `json:"nickname,optional" validate:"omitempty,max=128"`
}

type AuthRegisterResp struct {
	AccessToken  string          `json:"access_token"`
	RefreshToken string          `json:"refresh_token"`
	ExpiresIn    int64           `json:"expires_in"`
	TokenType    string          `json:"token_type"`
	SessionId    string          `json:"session_id"`
	User         AuthUserProfile `json:"user"`
	Session      AuthSessionView `json:"session"`
}

type AuthSessionView struct {
	SessionId  string `json:"session_id"`
	UserId     string `json:"user_id"`
	AuthSource string `json:"auth_source"`
	ClientType string `json:"client_type,optional"`
	DeviceId   string `json:"device_id,optional"`
	DeviceName string `json:"device_name,optional"`
	Status     string `json:"status"`
	LastSeenAt int64  `json:"last_seen_at,optional"`
	ExpiresAt  int64  `json:"expires_at,optional"`
}

type AuthSsoCallbackReq struct {
	Provider    string `json:"provider" validate:"required,min=1,max=64"`
	Code        string `json:"code" validate:"required,min=1,max=4096"`
	State       string `json:"state" validate:"required,min=1,max=512"`
	RedirectUri string `json:"redirect_uri" validate:"required,url,max=2048"`
	ClientType  string `json:"client_type,optional" validate:"omitempty,max=32"`
	DeviceId    string `json:"device_id,optional" validate:"omitempty,max=128"`
	DeviceName  string `json:"device_name,optional" validate:"omitempty,max=128"`
	UserAgent   string `json:"user_agent,optional" validate:"omitempty,max=512"`
}

type AuthSsoCallbackResp struct {
	AccessToken  string          `json:"access_token"`
	RefreshToken string          `json:"refresh_token"`
	ExpiresIn    int64           `json:"expires_in"`
	TokenType    string          `json:"token_type"`
	SessionId    string          `json:"session_id"`
	User         AuthUserProfile `json:"user"`
	Session      AuthSessionView `json:"session"`
}

type AuthSsoStartReq struct {
	Provider    string `json:"provider" validate:"required,min=1,max=64"`
	RedirectUri string `json:"redirect_uri" validate:"required,url,max=2048"`
	State       string `json:"state,optional" validate:"omitempty,max=512"`
}

type AuthSsoStartResp struct {
	Provider string `json:"provider"`
	AuthUrl  string `json:"auth_url"`
	State    string `json:"state"`
}

type AuthUserProfile struct {
	UserId    string `json:"user_id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Nickname  string `json:"nickname,optional"`
	AvatarUrl string `json:"avatar_url,optional"`
	Role      string `json:"role"`
	Status    string `json:"status"`
}

type HealthzResp struct {
	Status string `json:"status"`
}

type ReadyzResp struct {
	Status string `json:"status"`
}

type WsStubResp struct {
	Ok bool `json:"ok"`
}
