// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: v3/proto/content.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Content_CreateContent_FullMethodName          = "/content.Content/CreateContent"
	Content_UpdateContent_FullMethodName          = "/content.Content/UpdateContent"
	Content_GetContent_FullMethodName             = "/content.Content/GetContent"
	Content_ListStudioContents_FullMethodName     = "/content.Content/ListStudioContents"
	Content_ArchiveContent_FullMethodName         = "/content.Content/ArchiveContent"
	Content_ListContentRevisions_FullMethodName   = "/content.Content/ListContentRevisions"
	Content_GetContentRevision_FullMethodName     = "/content.Content/GetContentRevision"
	Content_CreateContentRelation_FullMethodName  = "/content.Content/CreateContentRelation"
	Content_DeleteContentRelation_FullMethodName  = "/content.Content/DeleteContentRelation"
	Content_ListContentRelations_FullMethodName   = "/content.Content/ListContentRelations"
	Content_CreateTag_FullMethodName              = "/content.Content/CreateTag"
	Content_UpdateTag_FullMethodName              = "/content.Content/UpdateTag"
	Content_DeleteTag_FullMethodName              = "/content.Content/DeleteTag"
	Content_ListTags_FullMethodName               = "/content.Content/ListTags"
	Content_ListPublicContents_FullMethodName     = "/content.Content/ListPublicContents"
	Content_GetPublicContentBySlug_FullMethodName = "/content.Content/GetPublicContentBySlug"
	Content_Ping_FullMethodName                   = "/content.Content/Ping"
)

// ContentClient is the client API for Content service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContentClient interface {
	CreateContent(ctx context.Context, in *CreateContentRequest, opts ...grpc.CallOption) (*CreateContentResponse, error)
	UpdateContent(ctx context.Context, in *UpdateContentRequest, opts ...grpc.CallOption) (*UpdateContentResponse, error)
	GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*GetContentResponse, error)
	ListStudioContents(ctx context.Context, in *ListStudioContentsRequest, opts ...grpc.CallOption) (*ListStudioContentsResponse, error)
	ArchiveContent(ctx context.Context, in *ArchiveContentRequest, opts ...grpc.CallOption) (*ArchiveContentResponse, error)
	ListContentRevisions(ctx context.Context, in *ListContentRevisionsRequest, opts ...grpc.CallOption) (*ListContentRevisionsResponse, error)
	GetContentRevision(ctx context.Context, in *GetContentRevisionRequest, opts ...grpc.CallOption) (*GetContentRevisionResponse, error)
	CreateContentRelation(ctx context.Context, in *CreateContentRelationRequest, opts ...grpc.CallOption) (*CreateContentRelationResponse, error)
	DeleteContentRelation(ctx context.Context, in *DeleteContentRelationRequest, opts ...grpc.CallOption) (*DeleteContentRelationResponse, error)
	ListContentRelations(ctx context.Context, in *ListContentRelationsRequest, opts ...grpc.CallOption) (*ListContentRelationsResponse, error)
	CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error)
	UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*UpdateTagResponse, error)
	DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error)
	ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error)
	ListPublicContents(ctx context.Context, in *ListPublicContentsRequest, opts ...grpc.CallOption) (*ListPublicContentsResponse, error)
	GetPublicContentBySlug(ctx context.Context, in *GetPublicContentBySlugRequest, opts ...grpc.CallOption) (*GetPublicContentBySlugResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type contentClient struct {
	cc grpc.ClientConnInterface
}

func NewContentClient(cc grpc.ClientConnInterface) ContentClient {
	return &contentClient{cc}
}

func (c *contentClient) CreateContent(ctx context.Context, in *CreateContentRequest, opts ...grpc.CallOption) (*CreateContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateContentResponse)
	err := c.cc.Invoke(ctx, Content_CreateContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) UpdateContent(ctx context.Context, in *UpdateContentRequest, opts ...grpc.CallOption) (*UpdateContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateContentResponse)
	err := c.cc.Invoke(ctx, Content_UpdateContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*GetContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContentResponse)
	err := c.cc.Invoke(ctx, Content_GetContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) ListStudioContents(ctx context.Context, in *ListStudioContentsRequest, opts ...grpc.CallOption) (*ListStudioContentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStudioContentsResponse)
	err := c.cc.Invoke(ctx, Content_ListStudioContents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) ArchiveContent(ctx context.Context, in *ArchiveContentRequest, opts ...grpc.CallOption) (*ArchiveContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArchiveContentResponse)
	err := c.cc.Invoke(ctx, Content_ArchiveContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) ListContentRevisions(ctx context.Context, in *ListContentRevisionsRequest, opts ...grpc.CallOption) (*ListContentRevisionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContentRevisionsResponse)
	err := c.cc.Invoke(ctx, Content_ListContentRevisions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) GetContentRevision(ctx context.Context, in *GetContentRevisionRequest, opts ...grpc.CallOption) (*GetContentRevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContentRevisionResponse)
	err := c.cc.Invoke(ctx, Content_GetContentRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) CreateContentRelation(ctx context.Context, in *CreateContentRelationRequest, opts ...grpc.CallOption) (*CreateContentRelationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateContentRelationResponse)
	err := c.cc.Invoke(ctx, Content_CreateContentRelation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) DeleteContentRelation(ctx context.Context, in *DeleteContentRelationRequest, opts ...grpc.CallOption) (*DeleteContentRelationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteContentRelationResponse)
	err := c.cc.Invoke(ctx, Content_DeleteContentRelation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) ListContentRelations(ctx context.Context, in *ListContentRelationsRequest, opts ...grpc.CallOption) (*ListContentRelationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContentRelationsResponse)
	err := c.cc.Invoke(ctx, Content_ListContentRelations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTagResponse)
	err := c.cc.Invoke(ctx, Content_CreateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*UpdateTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTagResponse)
	err := c.cc.Invoke(ctx, Content_UpdateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTagResponse)
	err := c.cc.Invoke(ctx, Content_DeleteTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTagsResponse)
	err := c.cc.Invoke(ctx, Content_ListTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) ListPublicContents(ctx context.Context, in *ListPublicContentsRequest, opts ...grpc.CallOption) (*ListPublicContentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPublicContentsResponse)
	err := c.cc.Invoke(ctx, Content_ListPublicContents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) GetPublicContentBySlug(ctx context.Context, in *GetPublicContentBySlugRequest, opts ...grpc.CallOption) (*GetPublicContentBySlugResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublicContentBySlugResponse)
	err := c.cc.Invoke(ctx, Content_GetPublicContentBySlug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, Content_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentServer is the server API for Content service.
// All implementations must embed UnimplementedContentServer
// for forward compatibility.
type ContentServer interface {
	CreateContent(context.Context, *CreateContentRequest) (*CreateContentResponse, error)
	UpdateContent(context.Context, *UpdateContentRequest) (*UpdateContentResponse, error)
	GetContent(context.Context, *GetContentRequest) (*GetContentResponse, error)
	ListStudioContents(context.Context, *ListStudioContentsRequest) (*ListStudioContentsResponse, error)
	ArchiveContent(context.Context, *ArchiveContentRequest) (*ArchiveContentResponse, error)
	ListContentRevisions(context.Context, *ListContentRevisionsRequest) (*ListContentRevisionsResponse, error)
	GetContentRevision(context.Context, *GetContentRevisionRequest) (*GetContentRevisionResponse, error)
	CreateContentRelation(context.Context, *CreateContentRelationRequest) (*CreateContentRelationResponse, error)
	DeleteContentRelation(context.Context, *DeleteContentRelationRequest) (*DeleteContentRelationResponse, error)
	ListContentRelations(context.Context, *ListContentRelationsRequest) (*ListContentRelationsResponse, error)
	CreateTag(context.Context, *CreateTagRequest) (*CreateTagResponse, error)
	UpdateTag(context.Context, *UpdateTagRequest) (*UpdateTagResponse, error)
	DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error)
	ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error)
	ListPublicContents(context.Context, *ListPublicContentsRequest) (*ListPublicContentsResponse, error)
	GetPublicContentBySlug(context.Context, *GetPublicContentBySlugRequest) (*GetPublicContentBySlugResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedContentServer()
}

// UnimplementedContentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContentServer struct{}

func (UnimplementedContentServer) CreateContent(context.Context, *CreateContentRequest) (*CreateContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateContent not implemented")
}
func (UnimplementedContentServer) UpdateContent(context.Context, *UpdateContentRequest) (*UpdateContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateContent not implemented")
}
func (UnimplementedContentServer) GetContent(context.Context, *GetContentRequest) (*GetContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContent not implemented")
}
func (UnimplementedContentServer) ListStudioContents(context.Context, *ListStudioContentsRequest) (*ListStudioContentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStudioContents not implemented")
}
func (UnimplementedContentServer) ArchiveContent(context.Context, *ArchiveContentRequest) (*ArchiveContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveContent not implemented")
}
func (UnimplementedContentServer) ListContentRevisions(context.Context, *ListContentRevisionsRequest) (*ListContentRevisionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListContentRevisions not implemented")
}
func (UnimplementedContentServer) GetContentRevision(context.Context, *GetContentRevisionRequest) (*GetContentRevisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContentRevision not implemented")
}
func (UnimplementedContentServer) CreateContentRelation(context.Context, *CreateContentRelationRequest) (*CreateContentRelationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateContentRelation not implemented")
}
func (UnimplementedContentServer) DeleteContentRelation(context.Context, *DeleteContentRelationRequest) (*DeleteContentRelationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteContentRelation not implemented")
}
func (UnimplementedContentServer) ListContentRelations(context.Context, *ListContentRelationsRequest) (*ListContentRelationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListContentRelations not implemented")
}
func (UnimplementedContentServer) CreateTag(context.Context, *CreateTagRequest) (*CreateTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTag not implemented")
}
func (UnimplementedContentServer) UpdateTag(context.Context, *UpdateTagRequest) (*UpdateTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTag not implemented")
}
func (UnimplementedContentServer) DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTag not implemented")
}
func (UnimplementedContentServer) ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTags not implemented")
}
func (UnimplementedContentServer) ListPublicContents(context.Context, *ListPublicContentsRequest) (*ListPublicContentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPublicContents not implemented")
}
func (UnimplementedContentServer) GetPublicContentBySlug(context.Context, *GetPublicContentBySlugRequest) (*GetPublicContentBySlugResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublicContentBySlug not implemented")
}
func (UnimplementedContentServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedContentServer) mustEmbedUnimplementedContentServer() {}
func (UnimplementedContentServer) testEmbeddedByValue()                 {}

// UnsafeContentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentServer will
// result in compilation errors.
type UnsafeContentServer interface {
	mustEmbedUnimplementedContentServer()
}

func RegisterContentServer(s grpc.ServiceRegistrar, srv ContentServer) {
	// If the following call panics, it indicates UnimplementedContentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Content_ServiceDesc, srv)
}

func _Content_CreateContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).CreateContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_CreateContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).CreateContent(ctx, req.(*CreateContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_UpdateContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).UpdateContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_UpdateContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).UpdateContent(ctx, req.(*UpdateContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_GetContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).GetContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_GetContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).GetContent(ctx, req.(*GetContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_ListStudioContents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStudioContentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).ListStudioContents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_ListStudioContents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).ListStudioContents(ctx, req.(*ListStudioContentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_ArchiveContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).ArchiveContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_ArchiveContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).ArchiveContent(ctx, req.(*ArchiveContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_ListContentRevisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContentRevisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).ListContentRevisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_ListContentRevisions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).ListContentRevisions(ctx, req.(*ListContentRevisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_GetContentRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).GetContentRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_GetContentRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).GetContentRevision(ctx, req.(*GetContentRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_CreateContentRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContentRelationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).CreateContentRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_CreateContentRelation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).CreateContentRelation(ctx, req.(*CreateContentRelationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_DeleteContentRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContentRelationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).DeleteContentRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_DeleteContentRelation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).DeleteContentRelation(ctx, req.(*DeleteContentRelationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_ListContentRelations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContentRelationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).ListContentRelations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_ListContentRelations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).ListContentRelations(ctx, req.(*ListContentRelationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_CreateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).CreateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_CreateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).CreateTag(ctx, req.(*CreateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_UpdateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).UpdateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_UpdateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).UpdateTag(ctx, req.(*UpdateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_DeleteTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).DeleteTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_DeleteTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).DeleteTag(ctx, req.(*DeleteTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_ListTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).ListTags(ctx, req.(*ListTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_ListPublicContents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPublicContentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).ListPublicContents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_ListPublicContents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).ListPublicContents(ctx, req.(*ListPublicContentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_GetPublicContentBySlug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicContentBySlugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).GetPublicContentBySlug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_GetPublicContentBySlug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).GetPublicContentBySlug(ctx, req.(*GetPublicContentBySlugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Content_ServiceDesc is the grpc.ServiceDesc for Content service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Content_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "content.Content",
	HandlerType: (*ContentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContent",
			Handler:    _Content_CreateContent_Handler,
		},
		{
			MethodName: "UpdateContent",
			Handler:    _Content_UpdateContent_Handler,
		},
		{
			MethodName: "GetContent",
			Handler:    _Content_GetContent_Handler,
		},
		{
			MethodName: "ListStudioContents",
			Handler:    _Content_ListStudioContents_Handler,
		},
		{
			MethodName: "ArchiveContent",
			Handler:    _Content_ArchiveContent_Handler,
		},
		{
			MethodName: "ListContentRevisions",
			Handler:    _Content_ListContentRevisions_Handler,
		},
		{
			MethodName: "GetContentRevision",
			Handler:    _Content_GetContentRevision_Handler,
		},
		{
			MethodName: "CreateContentRelation",
			Handler:    _Content_CreateContentRelation_Handler,
		},
		{
			MethodName: "DeleteContentRelation",
			Handler:    _Content_DeleteContentRelation_Handler,
		},
		{
			MethodName: "ListContentRelations",
			Handler:    _Content_ListContentRelations_Handler,
		},
		{
			MethodName: "CreateTag",
			Handler:    _Content_CreateTag_Handler,
		},
		{
			MethodName: "UpdateTag",
			Handler:    _Content_UpdateTag_Handler,
		},
		{
			MethodName: "DeleteTag",
			Handler:    _Content_DeleteTag_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _Content_ListTags_Handler,
		},
		{
			MethodName: "ListPublicContents",
			Handler:    _Content_ListPublicContents_Handler,
		},
		{
			MethodName: "GetPublicContentBySlug",
			Handler:    _Content_GetPublicContentBySlug_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Content_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v3/proto/content.proto",
}
