// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: content.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive-Blog-V3/services/content/internal/logic"
	"github.com/HappyLadySauce/Beehive-Blog-V3/services/content/internal/svc"
	"github.com/HappyLadySauce/Beehive-Blog-V3/services/content/pb"
)

type ContentServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedContentServer
}

func NewContentServer(svcCtx *svc.ServiceContext) *ContentServer {
	return &ContentServer{
		svcCtx: svcCtx,
	}
}

func (s *ContentServer) CreateContent(ctx context.Context, in *pb.CreateContentRequest) (*pb.CreateContentResponse, error) {
	l := logic.NewCreateContentLogic(ctx, s.svcCtx)
	return l.CreateContent(in)
}

func (s *ContentServer) UpdateContent(ctx context.Context, in *pb.UpdateContentRequest) (*pb.UpdateContentResponse, error) {
	l := logic.NewUpdateContentLogic(ctx, s.svcCtx)
	return l.UpdateContent(in)
}

func (s *ContentServer) GetContent(ctx context.Context, in *pb.GetContentRequest) (*pb.GetContentResponse, error) {
	l := logic.NewGetContentLogic(ctx, s.svcCtx)
	return l.GetContent(in)
}

func (s *ContentServer) ListStudioContents(ctx context.Context, in *pb.ListStudioContentsRequest) (*pb.ListStudioContentsResponse, error) {
	l := logic.NewListStudioContentsLogic(ctx, s.svcCtx)
	return l.ListStudioContents(in)
}

func (s *ContentServer) ArchiveContent(ctx context.Context, in *pb.ArchiveContentRequest) (*pb.ArchiveContentResponse, error) {
	l := logic.NewArchiveContentLogic(ctx, s.svcCtx)
	return l.ArchiveContent(in)
}

func (s *ContentServer) ListContentRevisions(ctx context.Context, in *pb.ListContentRevisionsRequest) (*pb.ListContentRevisionsResponse, error) {
	l := logic.NewListContentRevisionsLogic(ctx, s.svcCtx)
	return l.ListContentRevisions(in)
}

func (s *ContentServer) GetContentRevision(ctx context.Context, in *pb.GetContentRevisionRequest) (*pb.GetContentRevisionResponse, error) {
	l := logic.NewGetContentRevisionLogic(ctx, s.svcCtx)
	return l.GetContentRevision(in)
}

func (s *ContentServer) CreateContentRelation(ctx context.Context, in *pb.CreateContentRelationRequest) (*pb.CreateContentRelationResponse, error) {
	l := logic.NewCreateContentRelationLogic(ctx, s.svcCtx)
	return l.CreateContentRelation(in)
}

func (s *ContentServer) DeleteContentRelation(ctx context.Context, in *pb.DeleteContentRelationRequest) (*pb.DeleteContentRelationResponse, error) {
	l := logic.NewDeleteContentRelationLogic(ctx, s.svcCtx)
	return l.DeleteContentRelation(in)
}

func (s *ContentServer) ListContentRelations(ctx context.Context, in *pb.ListContentRelationsRequest) (*pb.ListContentRelationsResponse, error) {
	l := logic.NewListContentRelationsLogic(ctx, s.svcCtx)
	return l.ListContentRelations(in)
}

func (s *ContentServer) CreateTag(ctx context.Context, in *pb.CreateTagRequest) (*pb.CreateTagResponse, error) {
	l := logic.NewCreateTagLogic(ctx, s.svcCtx)
	return l.CreateTag(in)
}

func (s *ContentServer) UpdateTag(ctx context.Context, in *pb.UpdateTagRequest) (*pb.UpdateTagResponse, error) {
	l := logic.NewUpdateTagLogic(ctx, s.svcCtx)
	return l.UpdateTag(in)
}

func (s *ContentServer) DeleteTag(ctx context.Context, in *pb.DeleteTagRequest) (*pb.DeleteTagResponse, error) {
	l := logic.NewDeleteTagLogic(ctx, s.svcCtx)
	return l.DeleteTag(in)
}

func (s *ContentServer) ListTags(ctx context.Context, in *pb.ListTagsRequest) (*pb.ListTagsResponse, error) {
	l := logic.NewListTagsLogic(ctx, s.svcCtx)
	return l.ListTags(in)
}

func (s *ContentServer) ListPublicContents(ctx context.Context, in *pb.ListPublicContentsRequest) (*pb.ListPublicContentsResponse, error) {
	l := logic.NewListPublicContentsLogic(ctx, s.svcCtx)
	return l.ListPublicContents(in)
}

func (s *ContentServer) GetPublicContentBySlug(ctx context.Context, in *pb.GetPublicContentBySlugRequest) (*pb.GetPublicContentBySlugResponse, error) {
	l := logic.NewGetPublicContentBySlugLogic(ctx, s.svcCtx)
	return l.GetPublicContentBySlug(in)
}

func (s *ContentServer) Ping(ctx context.Context, in *pb.PingRequest) (*pb.PingResponse, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
