// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: file.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive-Blog-V3/services/file/internal/logic"
	"github.com/HappyLadySauce/Beehive-Blog-V3/services/file/internal/svc"
	"github.com/HappyLadySauce/Beehive-Blog-V3/services/file/pb"
)

type FileServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFileServiceServer
}

func NewFileServiceServer(svcCtx *svc.ServiceContext) *FileServiceServer {
	return &FileServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *FileServiceServer) Ping(ctx context.Context, in *pb.PingRequest) (*pb.PingResponse, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *FileServiceServer) CreateUpload(ctx context.Context, in *pb.CreateUploadRequest) (*pb.CreateUploadResponse, error) {
	l := logic.NewCreateUploadLogic(ctx, s.svcCtx)
	return l.CreateUpload(in)
}

func (s *FileServiceServer) CompleteUpload(ctx context.Context, in *pb.CompleteUploadRequest) (*pb.AssetResponse, error) {
	l := logic.NewCompleteUploadLogic(ctx, s.svcCtx)
	return l.CompleteUpload(in)
}

func (s *FileServiceServer) ListAssets(ctx context.Context, in *pb.ListAssetsRequest) (*pb.ListAssetsResponse, error) {
	l := logic.NewListAssetsLogic(ctx, s.svcCtx)
	return l.ListAssets(in)
}

func (s *FileServiceServer) GetAsset(ctx context.Context, in *pb.GetAssetRequest) (*pb.AssetResponse, error) {
	l := logic.NewGetAssetLogic(ctx, s.svcCtx)
	return l.GetAsset(in)
}

func (s *FileServiceServer) DeleteAsset(ctx context.Context, in *pb.DeleteAssetRequest) (*pb.DeleteAssetResponse, error) {
	l := logic.NewDeleteAssetLogic(ctx, s.svcCtx)
	return l.DeleteAsset(in)
}
