// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: identity.proto

package identity

import (
	"context"

	"github.com/HappyLadySauce/Beehive-Blog-V3/services/identity/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CurrentUser                   = pb.CurrentUser
	FederatedIdentity             = pb.FederatedIdentity
	FinishSsoLoginRequest         = pb.FinishSsoLoginRequest
	FinishSsoLoginResponse        = pb.FinishSsoLoginResponse
	GetCurrentUserRequest         = pb.GetCurrentUserRequest
	GetCurrentUserResponse        = pb.GetCurrentUserResponse
	IntrospectAccessTokenRequest  = pb.IntrospectAccessTokenRequest
	IntrospectAccessTokenResponse = pb.IntrospectAccessTokenResponse
	LoginLocalUserRequest         = pb.LoginLocalUserRequest
	LoginLocalUserResponse        = pb.LoginLocalUserResponse
	LogoutSessionRequest          = pb.LogoutSessionRequest
	LogoutSessionResponse         = pb.LogoutSessionResponse
	RefreshSessionTokenRequest    = pb.RefreshSessionTokenRequest
	RefreshSessionTokenResponse   = pb.RefreshSessionTokenResponse
	RegisterLocalUserRequest      = pb.RegisterLocalUserRequest
	RegisterLocalUserResponse     = pb.RegisterLocalUserResponse
	SessionInfo                   = pb.SessionInfo
	StartSsoLoginRequest          = pb.StartSsoLoginRequest
	StartSsoLoginResponse         = pb.StartSsoLoginResponse
	TokenPair                     = pb.TokenPair

	Identity interface {
		RegisterLocalUser(ctx context.Context, in *RegisterLocalUserRequest, opts ...grpc.CallOption) (*RegisterLocalUserResponse, error)
		LoginLocalUser(ctx context.Context, in *LoginLocalUserRequest, opts ...grpc.CallOption) (*LoginLocalUserResponse, error)
		StartSsoLogin(ctx context.Context, in *StartSsoLoginRequest, opts ...grpc.CallOption) (*StartSsoLoginResponse, error)
		FinishSsoLogin(ctx context.Context, in *FinishSsoLoginRequest, opts ...grpc.CallOption) (*FinishSsoLoginResponse, error)
		RefreshSessionToken(ctx context.Context, in *RefreshSessionTokenRequest, opts ...grpc.CallOption) (*RefreshSessionTokenResponse, error)
		LogoutSession(ctx context.Context, in *LogoutSessionRequest, opts ...grpc.CallOption) (*LogoutSessionResponse, error)
		GetCurrentUser(ctx context.Context, in *GetCurrentUserRequest, opts ...grpc.CallOption) (*GetCurrentUserResponse, error)
		IntrospectAccessToken(ctx context.Context, in *IntrospectAccessTokenRequest, opts ...grpc.CallOption) (*IntrospectAccessTokenResponse, error)
	}

	defaultIdentity struct {
		cli zrpc.Client
	}
)

func NewIdentity(cli zrpc.Client) Identity {
	return &defaultIdentity{
		cli: cli,
	}
}

func (m *defaultIdentity) RegisterLocalUser(ctx context.Context, in *RegisterLocalUserRequest, opts ...grpc.CallOption) (*RegisterLocalUserResponse, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.RegisterLocalUser(ctx, in, opts...)
}

func (m *defaultIdentity) LoginLocalUser(ctx context.Context, in *LoginLocalUserRequest, opts ...grpc.CallOption) (*LoginLocalUserResponse, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.LoginLocalUser(ctx, in, opts...)
}

func (m *defaultIdentity) StartSsoLogin(ctx context.Context, in *StartSsoLoginRequest, opts ...grpc.CallOption) (*StartSsoLoginResponse, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.StartSsoLogin(ctx, in, opts...)
}

func (m *defaultIdentity) FinishSsoLogin(ctx context.Context, in *FinishSsoLoginRequest, opts ...grpc.CallOption) (*FinishSsoLoginResponse, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.FinishSsoLogin(ctx, in, opts...)
}

func (m *defaultIdentity) RefreshSessionToken(ctx context.Context, in *RefreshSessionTokenRequest, opts ...grpc.CallOption) (*RefreshSessionTokenResponse, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.RefreshSessionToken(ctx, in, opts...)
}

func (m *defaultIdentity) LogoutSession(ctx context.Context, in *LogoutSessionRequest, opts ...grpc.CallOption) (*LogoutSessionResponse, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.LogoutSession(ctx, in, opts...)
}

func (m *defaultIdentity) GetCurrentUser(ctx context.Context, in *GetCurrentUserRequest, opts ...grpc.CallOption) (*GetCurrentUserResponse, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.GetCurrentUser(ctx, in, opts...)
}

func (m *defaultIdentity) IntrospectAccessToken(ctx context.Context, in *IntrospectAccessTokenRequest, opts ...grpc.CallOption) (*IntrospectAccessTokenResponse, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.IntrospectAccessToken(ctx, in, opts...)
}
